/* Generated by Yosys 0.7+281 (git sha1 d38a64b, gcc 4.9.2-10 -fPIC -Os) */

(* top =  1  *)
(* src = "fsm.v:5" *)
module fsm(clk, reset, init, FIFOpause0, FIFOpause1, FIFOpause2, FIFOpause3, FIFOcontinue0, FIFOcontinue1, FIFOcontinue2, FIFOcontinue3, FIFOempty0, FIFOempty1, FIFOempty2, FIFOempty3, FIFOerror0, FIFOerror1, FIFOerror2, FIFOerror3, FIFOfull0, FIFOfull1, FIFOfull2, FIFOfull3, error_full, pause, continue, idle);
  (* src = "fsm.v:122" *)
  wire [3:0] _000_;
  (* src = "fsm.v:122" *)
  wire _001_;
  (* src = "fsm.v:109" *)
  wire [8:0] _002_;
  (* src = "fsm.v:122" *)
  wire [3:0] _003_;
  (* src = "fsm.v:109" *)
  wire [8:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  (* src = "fsm.v:63" *)
  wire [3:0] FIFOcontinue;
  (* src = "fsm.v:22" *)
  input FIFOcontinue0;
  (* src = "fsm.v:23" *)
  input FIFOcontinue1;
  (* src = "fsm.v:24" *)
  input FIFOcontinue2;
  (* src = "fsm.v:25" *)
  input FIFOcontinue3;
  (* src = "fsm.v:64" *)
  wire [3:0] FIFOempty;
  (* src = "fsm.v:26" *)
  input FIFOempty0;
  (* src = "fsm.v:27" *)
  input FIFOempty1;
  (* src = "fsm.v:28" *)
  input FIFOempty2;
  (* src = "fsm.v:29" *)
  input FIFOempty3;
  (* src = "fsm.v:66" *)
  wire [3:0] FIFOerror;
  (* src = "fsm.v:30" *)
  input FIFOerror0;
  (* src = "fsm.v:31" *)
  input FIFOerror1;
  (* src = "fsm.v:32" *)
  input FIFOerror2;
  (* src = "fsm.v:33" *)
  input FIFOerror3;
  (* src = "fsm.v:65" *)
  wire [3:0] FIFOfull;
  (* src = "fsm.v:34" *)
  input FIFOfull0;
  (* src = "fsm.v:35" *)
  input FIFOfull1;
  (* src = "fsm.v:36" *)
  input FIFOfull2;
  (* src = "fsm.v:37" *)
  input FIFOfull3;
  (* src = "fsm.v:62" *)
  wire [3:0] FIFOpause;
  (* src = "fsm.v:17" *)
  input FIFOpause0;
  (* src = "fsm.v:18" *)
  input FIFOpause1;
  (* src = "fsm.v:19" *)
  input FIFOpause2;
  (* src = "fsm.v:20" *)
  input FIFOpause3;
  (* src = "fsm.v:13" *)
  input clk;
  (* src = "fsm.v:41" *)
  output [3:0] continue;
  (* src = "fsm.v:39" *)
  output [3:0] error_full;
  (* src = "fsm.v:42" *)
  output idle;
  (* src = "fsm.v:15" *)
  input init;
  (* src = "fsm.v:49" *)
  wire [8:0] nxtState;
  (* src = "fsm.v:40" *)
  output [3:0] pause;
  (* src = "fsm.v:14" *)
  input reset;
  (* src = "fsm.v:49" *)
  wire [8:0] state;
  NOT _198_ (
    .A(FIFOerror0),
    .Y(_176_)
  );
  NOT _199_ (
    .A(FIFOerror1),
    .Y(_177_)
  );
  NOT _200_ (
    .A(FIFOerror2),
    .Y(_178_)
  );
  NOT _201_ (
    .A(FIFOerror3),
    .Y(_179_)
  );
  NOT _202_ (
    .A(state[6]),
    .Y(_180_)
  );
  NOT _203_ (
    .A(state[8]),
    .Y(_181_)
  );
  NOT _204_ (
    .A(state[0]),
    .Y(_182_)
  );
  NOT _205_ (
    .A(state[1]),
    .Y(_183_)
  );
  NOT _206_ (
    .A(state[3]),
    .Y(_184_)
  );
  NOT _207_ (
    .A(state[2]),
    .Y(_185_)
  );
  NOT _208_ (
    .A(state[4]),
    .Y(_186_)
  );
  NOT _209_ (
    .A(state[5]),
    .Y(_187_)
  );
  NOT _210_ (
    .A(state[7]),
    .Y(_188_)
  );
  NOT _211_ (
    .A(init),
    .Y(_189_)
  );
  NOR _212_ (
    .A(state[8]),
    .B(state[0]),
    .Y(_190_)
  );
  NOT _213_ (
    .A(_190_),
    .Y(_191_)
  );
  NOR _214_ (
    .A(state[1]),
    .B(_191_),
    .Y(_192_)
  );
  NAND _215_ (
    .A(_183_),
    .B(_190_),
    .Y(_193_)
  );
  NOR _216_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_194_)
  );
  NAND _217_ (
    .A(_186_),
    .B(_187_),
    .Y(_195_)
  );
  NOR _218_ (
    .A(state[6]),
    .B(state[7]),
    .Y(_196_)
  );
  NAND _219_ (
    .A(_180_),
    .B(_188_),
    .Y(_197_)
  );
  NAND _220_ (
    .A(_194_),
    .B(_196_),
    .Y(_005_)
  );
  NOR _221_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_006_)
  );
  NAND _222_ (
    .A(_181_),
    .B(_196_),
    .Y(_007_)
  );
  NOR _223_ (
    .A(_195_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _224_ (
    .A(_193_),
    .B(_005_),
    .Y(_009_)
  );
  NAND _225_ (
    .A(_006_),
    .B(_008_),
    .Y(_010_)
  );
  NOR _226_ (
    .A(state[3]),
    .B(_185_),
    .Y(_011_)
  );
  NAND _227_ (
    .A(_009_),
    .B(_011_),
    .Y(_012_)
  );
  NOT _228_ (
    .A(_012_),
    .Y(_021_)
  );
  NAND _229_ (
    .A(FIFOempty0),
    .B(FIFOempty1),
    .Y(_013_)
  );
  NAND _230_ (
    .A(FIFOempty2),
    .B(FIFOempty3),
    .Y(_014_)
  );
  NOR _231_ (
    .A(_013_),
    .B(_014_),
    .Y(_001_)
  );
  NOR _232_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_015_)
  );
  NAND _233_ (
    .A(_184_),
    .B(_185_),
    .Y(_016_)
  );
  NOR _234_ (
    .A(_193_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _235_ (
    .A(_192_),
    .B(_015_),
    .Y(_018_)
  );
  NOR _236_ (
    .A(_195_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _237_ (
    .A(_194_),
    .B(_017_),
    .Y(_020_)
  );
  NAND _238_ (
    .A(state[6]),
    .B(_188_),
    .Y(_022_)
  );
  NOR _239_ (
    .A(_180_),
    .B(_020_),
    .Y(_023_)
  );
  NOR _240_ (
    .A(_020_),
    .B(_022_),
    .Y(_024_)
  );
  NAND _241_ (
    .A(_188_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _242_ (
    .A(_196_),
    .B(_017_),
    .Y(_026_)
  );
  NAND _243_ (
    .A(_186_),
    .B(state[5]),
    .Y(_027_)
  );
  NOR _244_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NOT _245_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _246_ (
    .A(state[4]),
    .B(_197_),
    .Y(_030_)
  );
  NAND _247_ (
    .A(state[5]),
    .B(_030_),
    .Y(_031_)
  );
  NOR _248_ (
    .A(_018_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _249_ (
    .A(_024_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _250_ (
    .A(_025_),
    .B(_029_),
    .Y(_034_)
  );
  NAND _251_ (
    .A(state[4]),
    .B(_187_),
    .Y(_035_)
  );
  NOR _252_ (
    .A(_026_),
    .B(_035_),
    .Y(_036_)
  );
  NOT _253_ (
    .A(_036_),
    .Y(_037_)
  );
  NOR _254_ (
    .A(_034_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _255_ (
    .A(_033_),
    .B(_037_),
    .Y(_039_)
  );
  NOR _256_ (
    .A(state[6]),
    .B(_188_),
    .Y(_040_)
  );
  NAND _257_ (
    .A(_019_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _258_ (
    .A(_181_),
    .B(_015_),
    .Y(_042_)
  );
  NOR _259_ (
    .A(_005_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _260_ (
    .A(state[0]),
    .B(_183_),
    .Y(_044_)
  );
  NAND _261_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _262_ (
    .A(_012_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _263_ (
    .A(_182_),
    .B(state[1]),
    .Y(_047_)
  );
  NAND _264_ (
    .A(_043_),
    .B(_047_),
    .Y(_048_)
  );
  NOT _265_ (
    .A(_048_),
    .Y(nxtState[1])
  );
  NOR _266_ (
    .A(_184_),
    .B(state[2]),
    .Y(_049_)
  );
  NAND _267_ (
    .A(state[3]),
    .B(_185_),
    .Y(_050_)
  );
  NOR _268_ (
    .A(_010_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _269_ (
    .A(_009_),
    .B(_049_),
    .Y(_052_)
  );
  NAND _270_ (
    .A(_048_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _271_ (
    .A(_046_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _272_ (
    .A(_041_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _273_ (
    .A(_188_),
    .B(_020_),
    .Y(_056_)
  );
  NAND _274_ (
    .A(_180_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _275_ (
    .A(_039_),
    .B(nxtState[1]),
    .Y(_058_)
  );
  NAND _276_ (
    .A(_052_),
    .B(_057_),
    .Y(_059_)
  );
  NOR _277_ (
    .A(_046_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _278_ (
    .A(_039_),
    .B(_055_),
    .Y(_061_)
  );
  NAND _279_ (
    .A(_058_),
    .B(_060_),
    .Y(_062_)
  );
  NOR _280_ (
    .A(state[0]),
    .B(reset),
    .Y(_063_)
  );
  NOR _281_ (
    .A(_041_),
    .B(_063_),
    .Y(_064_)
  );
  NOT _282_ (
    .A(_064_),
    .Y(_065_)
  );
  NAND _283_ (
    .A(_062_),
    .B(_065_),
    .Y(nxtState[0])
  );
  NOT _284_ (
    .A(nxtState[0]),
    .Y(_066_)
  );
  NAND _285_ (
    .A(_021_),
    .B(_001_),
    .Y(_067_)
  );
  NAND _286_ (
    .A(_045_),
    .B(_067_),
    .Y(nxtState[2])
  );
  NOT _287_ (
    .A(nxtState[2]),
    .Y(_068_)
  );
  NOR _288_ (
    .A(FIFOfull2),
    .B(FIFOpause2),
    .Y(_069_)
  );
  NOR _289_ (
    .A(FIFOfull1),
    .B(FIFOpause1),
    .Y(_070_)
  );
  NAND _290_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _291_ (
    .A(FIFOfull0),
    .B(FIFOpause0),
    .Y(_072_)
  );
  NOT _292_ (
    .A(_072_),
    .Y(_073_)
  );
  NOR _293_ (
    .A(FIFOfull3),
    .B(FIFOpause3),
    .Y(_074_)
  );
  NOT _294_ (
    .A(_074_),
    .Y(_075_)
  );
  NAND _295_ (
    .A(_072_),
    .B(_074_),
    .Y(_076_)
  );
  NOR _296_ (
    .A(_071_),
    .B(_076_),
    .Y(_077_)
  );
  NOT _297_ (
    .A(_077_),
    .Y(_078_)
  );
  NOR _298_ (
    .A(FIFOempty2),
    .B(FIFOcontinue2),
    .Y(_079_)
  );
  NOR _299_ (
    .A(FIFOempty1),
    .B(FIFOcontinue1),
    .Y(_080_)
  );
  NAND _300_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _301_ (
    .A(FIFOempty0),
    .B(FIFOcontinue0),
    .Y(_082_)
  );
  NOT _302_ (
    .A(_082_),
    .Y(_083_)
  );
  NOR _303_ (
    .A(FIFOempty3),
    .B(FIFOcontinue3),
    .Y(_084_)
  );
  NOT _304_ (
    .A(_084_),
    .Y(_085_)
  );
  NAND _305_ (
    .A(_082_),
    .B(_084_),
    .Y(_086_)
  );
  NOR _306_ (
    .A(_081_),
    .B(_086_),
    .Y(_087_)
  );
  NOT _307_ (
    .A(_087_),
    .Y(_088_)
  );
  NAND _308_ (
    .A(_077_),
    .B(_087_),
    .Y(_089_)
  );
  NOR _309_ (
    .A(_052_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _310_ (
    .A(FIFOerror0),
    .B(FIFOerror1),
    .Y(_091_)
  );
  NOT _311_ (
    .A(_091_),
    .Y(_092_)
  );
  NOR _312_ (
    .A(FIFOerror2),
    .B(FIFOerror3),
    .Y(_093_)
  );
  NOT _313_ (
    .A(_093_),
    .Y(_094_)
  );
  NOR _314_ (
    .A(_092_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _315_ (
    .A(_091_),
    .B(_093_),
    .Y(_096_)
  );
  NAND _316_ (
    .A(_090_),
    .B(_095_),
    .Y(_097_)
  );
  NOR _317_ (
    .A(_012_),
    .B(_001_),
    .Y(_098_)
  );
  NOR _318_ (
    .A(_039_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _319_ (
    .A(_097_),
    .B(_099_),
    .Y(nxtState[3])
  );
  NOT _320_ (
    .A(nxtState[3]),
    .Y(_100_)
  );
  NOR _321_ (
    .A(_052_),
    .B(_096_),
    .Y(_101_)
  );
  NOT _322_ (
    .A(_101_),
    .Y(_102_)
  );
  NAND _323_ (
    .A(_087_),
    .B(_101_),
    .Y(_103_)
  );
  NOT _324_ (
    .A(_103_),
    .Y(_104_)
  );
  NOR _325_ (
    .A(state[4]),
    .B(_078_),
    .Y(_105_)
  );
  NOR _326_ (
    .A(_061_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _327_ (
    .A(_104_),
    .B(_106_),
    .Y(_107_)
  );
  NOT _328_ (
    .A(_107_),
    .Y(nxtState[4])
  );
  NAND _329_ (
    .A(_077_),
    .B(_101_),
    .Y(_108_)
  );
  NOT _330_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _331_ (
    .A(state[5]),
    .B(_088_),
    .Y(_110_)
  );
  NOR _332_ (
    .A(_061_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _333_ (
    .A(_109_),
    .B(_111_),
    .Y(_112_)
  );
  NOT _334_ (
    .A(_112_),
    .Y(nxtState[5])
  );
  NOR _335_ (
    .A(_077_),
    .B(_087_),
    .Y(_113_)
  );
  NOR _336_ (
    .A(_180_),
    .B(_089_),
    .Y(_114_)
  );
  NOR _337_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _338_ (
    .A(_102_),
    .B(_115_),
    .Y(nxtState[6])
  );
  NOT _339_ (
    .A(nxtState[6]),
    .Y(_116_)
  );
  NOR _340_ (
    .A(reset),
    .B(_041_),
    .Y(_117_)
  );
  NOT _341_ (
    .A(_117_),
    .Y(_118_)
  );
  NAND _342_ (
    .A(_051_),
    .B(_096_),
    .Y(_119_)
  );
  NAND _343_ (
    .A(_118_),
    .B(_119_),
    .Y(nxtState[7])
  );
  NOT _344_ (
    .A(nxtState[7]),
    .Y(_120_)
  );
  NOR _345_ (
    .A(reset),
    .B(_189_),
    .Y(_121_)
  );
  NOR _346_ (
    .A(_066_),
    .B(_121_),
    .Y(_002_[0])
  );
  NOR _347_ (
    .A(nxtState[1]),
    .B(_121_),
    .Y(_122_)
  );
  NOT _348_ (
    .A(_122_),
    .Y(_002_[1])
  );
  NOR _349_ (
    .A(_068_),
    .B(_121_),
    .Y(_002_[2])
  );
  NOR _350_ (
    .A(_100_),
    .B(_121_),
    .Y(_002_[3])
  );
  NOR _351_ (
    .A(_107_),
    .B(_121_),
    .Y(_002_[4])
  );
  NOR _352_ (
    .A(_112_),
    .B(_121_),
    .Y(_002_[5])
  );
  NOR _353_ (
    .A(_116_),
    .B(_121_),
    .Y(_002_[6])
  );
  NOR _354_ (
    .A(_120_),
    .B(_121_),
    .Y(_002_[7])
  );
  NOR _355_ (
    .A(reset),
    .B(init),
    .Y(_123_)
  );
  NAND _356_ (
    .A(_189_),
    .B(nxtState[0]),
    .Y(_124_)
  );
  NOR _357_ (
    .A(_182_),
    .B(_189_),
    .Y(_125_)
  );
  NOR _358_ (
    .A(reset),
    .B(_125_),
    .Y(_126_)
  );
  NAND _359_ (
    .A(_124_),
    .B(_126_),
    .Y(_004_[0])
  );
  NAND _360_ (
    .A(state[1]),
    .B(_121_),
    .Y(_127_)
  );
  NAND _361_ (
    .A(nxtState[1]),
    .B(_123_),
    .Y(_128_)
  );
  NAND _362_ (
    .A(_127_),
    .B(_128_),
    .Y(_004_[1])
  );
  NAND _363_ (
    .A(state[2]),
    .B(_121_),
    .Y(_129_)
  );
  NAND _364_ (
    .A(nxtState[2]),
    .B(_123_),
    .Y(_130_)
  );
  NAND _365_ (
    .A(_129_),
    .B(_130_),
    .Y(_004_[2])
  );
  NAND _366_ (
    .A(state[3]),
    .B(_121_),
    .Y(_131_)
  );
  NAND _367_ (
    .A(nxtState[3]),
    .B(_123_),
    .Y(_132_)
  );
  NAND _368_ (
    .A(_131_),
    .B(_132_),
    .Y(_004_[3])
  );
  NAND _369_ (
    .A(state[4]),
    .B(_121_),
    .Y(_133_)
  );
  NOR _370_ (
    .A(_103_),
    .B(_105_),
    .Y(_134_)
  );
  NAND _371_ (
    .A(_123_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _372_ (
    .A(_133_),
    .B(_135_),
    .Y(_004_[4])
  );
  NAND _373_ (
    .A(state[5]),
    .B(_121_),
    .Y(_136_)
  );
  NOR _374_ (
    .A(_108_),
    .B(_110_),
    .Y(_137_)
  );
  NAND _375_ (
    .A(_123_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _376_ (
    .A(_136_),
    .B(_138_),
    .Y(_004_[5])
  );
  NAND _377_ (
    .A(state[6]),
    .B(_121_),
    .Y(_139_)
  );
  NAND _378_ (
    .A(nxtState[6]),
    .B(_123_),
    .Y(_140_)
  );
  NAND _379_ (
    .A(_139_),
    .B(_140_),
    .Y(_004_[6])
  );
  NAND _380_ (
    .A(state[7]),
    .B(_121_),
    .Y(_141_)
  );
  NAND _381_ (
    .A(nxtState[7]),
    .B(_123_),
    .Y(_142_)
  );
  NAND _382_ (
    .A(_141_),
    .B(_142_),
    .Y(_004_[7])
  );
  NAND _383_ (
    .A(state[8]),
    .B(_121_),
    .Y(_143_)
  );
  NOT _384_ (
    .A(_143_),
    .Y(_004_[8])
  );
  NOR _385_ (
    .A(_025_),
    .B(_079_),
    .Y(_144_)
  );
  NOR _386_ (
    .A(_032_),
    .B(_144_),
    .Y(_003_[2])
  );
  NOT _387_ (
    .A(_003_[2]),
    .Y(_000_[2])
  );
  NOR _388_ (
    .A(_025_),
    .B(_085_),
    .Y(_145_)
  );
  NOR _389_ (
    .A(_033_),
    .B(_145_),
    .Y(_000_[3])
  );
  NOT _390_ (
    .A(_000_[3]),
    .Y(_003_[3])
  );
  NOR _391_ (
    .A(_025_),
    .B(_083_),
    .Y(_146_)
  );
  NOR _392_ (
    .A(_033_),
    .B(_146_),
    .Y(_000_[0])
  );
  NOT _393_ (
    .A(_000_[0]),
    .Y(_003_[0])
  );
  NOR _394_ (
    .A(_025_),
    .B(_080_),
    .Y(_147_)
  );
  NOR _395_ (
    .A(_032_),
    .B(_147_),
    .Y(_003_[1])
  );
  NOT _396_ (
    .A(_003_[1]),
    .Y(_000_[1])
  );
  NOR _397_ (
    .A(_176_),
    .B(_041_),
    .Y(_168_)
  );
  NOR _398_ (
    .A(_177_),
    .B(_041_),
    .Y(_169_)
  );
  NOR _399_ (
    .A(_178_),
    .B(_041_),
    .Y(_170_)
  );
  NOR _400_ (
    .A(_179_),
    .B(_041_),
    .Y(_171_)
  );
  NOR _401_ (
    .A(_032_),
    .B(_069_),
    .Y(_148_)
  );
  NAND _402_ (
    .A(_034_),
    .B(_079_),
    .Y(_149_)
  );
  NAND _403_ (
    .A(_036_),
    .B(_069_),
    .Y(_150_)
  );
  NAND _404_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  NOT _405_ (
    .A(_151_),
    .Y(_152_)
  );
  NOR _406_ (
    .A(_148_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _407_ (
    .A(_038_),
    .B(_153_),
    .Y(_172_)
  );
  NOR _408_ (
    .A(_036_),
    .B(_145_),
    .Y(_154_)
  );
  NOR _409_ (
    .A(_075_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _410_ (
    .A(_028_),
    .B(_084_),
    .Y(_156_)
  );
  NAND _411_ (
    .A(_039_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _412_ (
    .A(_155_),
    .B(_157_),
    .Y(_173_)
  );
  NOR _413_ (
    .A(_036_),
    .B(_146_),
    .Y(_158_)
  );
  NOR _414_ (
    .A(_073_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _415_ (
    .A(_028_),
    .B(_082_),
    .Y(_160_)
  );
  NAND _416_ (
    .A(_039_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _417_ (
    .A(_159_),
    .B(_161_),
    .Y(_174_)
  );
  NOR _418_ (
    .A(_032_),
    .B(_070_),
    .Y(_162_)
  );
  NAND _419_ (
    .A(_034_),
    .B(_080_),
    .Y(_163_)
  );
  NAND _420_ (
    .A(_036_),
    .B(_070_),
    .Y(_164_)
  );
  NAND _421_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  NOT _422_ (
    .A(_165_),
    .Y(_166_)
  );
  NOR _423_ (
    .A(_162_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _424_ (
    .A(_038_),
    .B(_167_),
    .Y(_175_)
  );
  DFF _425_ (
    .C(clk),
    .D(_004_[0]),
    .Q(state[0])
  );
  DFF _426_ (
    .C(clk),
    .D(_004_[1]),
    .Q(state[1])
  );
  DFF _427_ (
    .C(clk),
    .D(_004_[2]),
    .Q(state[2])
  );
  DFF _428_ (
    .C(clk),
    .D(_004_[3]),
    .Q(state[3])
  );
  DFF _429_ (
    .C(clk),
    .D(_004_[4]),
    .Q(state[4])
  );
  DFF _430_ (
    .C(clk),
    .D(_004_[5]),
    .Q(state[5])
  );
  DFF _431_ (
    .C(clk),
    .D(_004_[6]),
    .Q(state[6])
  );
  DFF _432_ (
    .C(clk),
    .D(_004_[7]),
    .Q(state[7])
  );
  DFF _433_ (
    .C(clk),
    .D(_004_[8]),
    .Q(state[8])
  );
  DFF _434_ (
    .C(clk),
    .D(_002_[0]),
    .Q(nxtState[0])
  );
  DFF _435_ (
    .C(clk),
    .D(_002_[1]),
    .Q(nxtState[1])
  );
  DFF _436_ (
    .C(clk),
    .D(_002_[2]),
    .Q(nxtState[2])
  );
  DFF _437_ (
    .C(clk),
    .D(_002_[3]),
    .Q(nxtState[3])
  );
  DFF _438_ (
    .C(clk),
    .D(_002_[4]),
    .Q(nxtState[4])
  );
  DFF _439_ (
    .C(clk),
    .D(_002_[5]),
    .Q(nxtState[5])
  );
  DFF _440_ (
    .C(clk),
    .D(_002_[6]),
    .Q(nxtState[6])
  );
  DFF _441_ (
    .C(clk),
    .D(_002_[7]),
    .Q(nxtState[7])
  );
  DFF _442_ (
    .C(clk),
    .D(1'h0),
    .Q(1'h0)
  );
  \$_DLATCH_P_  _443_ (
    .D(1'h1),
    .E(_168_),
    .Q(error_full[0])
  );
  \$_DLATCH_P_  _444_ (
    .D(1'h1),
    .E(_169_),
    .Q(error_full[1])
  );
  \$_DLATCH_P_  _445_ (
    .D(1'h1),
    .E(_170_),
    .Q(error_full[2])
  );
  \$_DLATCH_P_  _446_ (
    .D(1'h1),
    .E(_171_),
    .Q(error_full[3])
  );
  \$_DLATCH_P_  _447_ (
    .D(_003_[0]),
    .E(_174_),
    .Q(pause[0])
  );
  \$_DLATCH_P_  _448_ (
    .D(_003_[1]),
    .E(_175_),
    .Q(pause[1])
  );
  \$_DLATCH_P_  _449_ (
    .D(_003_[2]),
    .E(_172_),
    .Q(pause[2])
  );
  \$_DLATCH_P_  _450_ (
    .D(_003_[3]),
    .E(_173_),
    .Q(pause[3])
  );
  \$_DLATCH_P_  _451_ (
    .D(_000_[0]),
    .E(_174_),
    .Q(continue[0])
  );
  \$_DLATCH_P_  _452_ (
    .D(_000_[1]),
    .E(_175_),
    .Q(continue[1])
  );
  \$_DLATCH_P_  _453_ (
    .D(_000_[2]),
    .E(_172_),
    .Q(continue[2])
  );
  \$_DLATCH_P_  _454_ (
    .D(_000_[3]),
    .E(_173_),
    .Q(continue[3])
  );
  \$_DLATCH_P_  _455_ (
    .D(_001_),
    .E(_021_),
    .Q(idle)
  );
  assign FIFOcontinue = { FIFOcontinue3, FIFOcontinue2, FIFOcontinue1, FIFOcontinue0 };
  assign FIFOempty = { FIFOempty3, FIFOempty2, FIFOempty1, FIFOempty0 };
  assign FIFOerror = { FIFOerror3, FIFOerror2, FIFOerror1, FIFOerror0 };
  assign FIFOfull = { FIFOfull3, FIFOfull2, FIFOfull1, FIFOfull0 };
  assign FIFOpause = { FIFOpause3, FIFOpause2, FIFOpause1, FIFOpause0 };
  assign nxtState[8] = 1'h0;
endmodule
