/* Generated by Yosys 0.7+281 (git sha1 d38a64b, gcc 4.9.2-10 -fPIC -Os) */

(* top =  1  *)
(* src = "fsm.v:5" *)
module fsm(clk, reset, init, FIFOpause0, FIFOpause1, FIFOpause2, FIFOpause3, FIFOcontinue0, FIFOcontinue1, FIFOcontinue2, FIFOcontinue3, FIFOempty0, FIFOempty1, FIFOempty2, FIFOempty3, FIFOerror0, FIFOerror1, FIFOerror2, FIFOerror3, FIFOfull0, FIFOfull1, FIFOfull2, FIFOfull3, error_full, pause, continue, idle);
  (* src = "fsm.v:109" *)
  wire _000_;
  (* src = "fsm.v:97" *)
  wire [8:0] _001_;
  (* src = "fsm.v:97" *)
  wire [8:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  (* src = "fsm.v:61" *)
  wire [3:0] FIFOcontinue;
  (* src = "fsm.v:20" *)
  input FIFOcontinue0;
  (* src = "fsm.v:21" *)
  input FIFOcontinue1;
  (* src = "fsm.v:22" *)
  input FIFOcontinue2;
  (* src = "fsm.v:23" *)
  input FIFOcontinue3;
  (* src = "fsm.v:62" *)
  wire [3:0] FIFOempty;
  (* src = "fsm.v:24" *)
  input FIFOempty0;
  (* src = "fsm.v:25" *)
  input FIFOempty1;
  (* src = "fsm.v:26" *)
  input FIFOempty2;
  (* src = "fsm.v:27" *)
  input FIFOempty3;
  (* src = "fsm.v:64" *)
  wire [3:0] FIFOerror;
  (* src = "fsm.v:28" *)
  input FIFOerror0;
  (* src = "fsm.v:29" *)
  input FIFOerror1;
  (* src = "fsm.v:30" *)
  input FIFOerror2;
  (* src = "fsm.v:31" *)
  input FIFOerror3;
  (* src = "fsm.v:63" *)
  wire [3:0] FIFOfull;
  (* src = "fsm.v:32" *)
  input FIFOfull0;
  (* src = "fsm.v:33" *)
  input FIFOfull1;
  (* src = "fsm.v:34" *)
  input FIFOfull2;
  (* src = "fsm.v:35" *)
  input FIFOfull3;
  (* src = "fsm.v:60" *)
  wire [3:0] FIFOpause;
  (* src = "fsm.v:16" *)
  input FIFOpause0;
  (* src = "fsm.v:17" *)
  input FIFOpause1;
  (* src = "fsm.v:18" *)
  input FIFOpause2;
  (* src = "fsm.v:19" *)
  input FIFOpause3;
  (* src = "fsm.v:13" *)
  input clk;
  (* src = "fsm.v:39" *)
  output [3:0] continue;
  (* src = "fsm.v:37" *)
  output [3:0] error_full;
  (* src = "fsm.v:40" *)
  output idle;
  (* src = "fsm.v:15" *)
  input init;
  (* src = "fsm.v:47" *)
  wire [8:0] nxtState;
  (* src = "fsm.v:38" *)
  output [3:0] pause;
  (* src = "fsm.v:14" *)
  input reset;
  (* src = "fsm.v:47" *)
  wire [8:0] state;
  NOT _170_ (
    .A(state[0]),
    .Y(_141_)
  );
  NOT _171_ (
    .A(state[8]),
    .Y(_142_)
  );
  NOT _172_ (
    .A(state[1]),
    .Y(_143_)
  );
  NOT _173_ (
    .A(state[2]),
    .Y(_144_)
  );
  NOT _174_ (
    .A(state[5]),
    .Y(_145_)
  );
  NOT _175_ (
    .A(state[4]),
    .Y(_146_)
  );
  NOT _176_ (
    .A(state[6]),
    .Y(_147_)
  );
  NOT _177_ (
    .A(state[7]),
    .Y(_148_)
  );
  NOT _178_ (
    .A(init),
    .Y(_149_)
  );
  NOT _179_ (
    .A(reset),
    .Y(_150_)
  );
  NOR _180_ (
    .A(state[5]),
    .B(state[4]),
    .Y(_151_)
  );
  NAND _181_ (
    .A(_145_),
    .B(_146_),
    .Y(_152_)
  );
  NOR _182_ (
    .A(state[6]),
    .B(state[7]),
    .Y(_153_)
  );
  NOT _183_ (
    .A(_153_),
    .Y(_154_)
  );
  NOR _184_ (
    .A(_152_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _185_ (
    .A(_151_),
    .B(_153_),
    .Y(_156_)
  );
  NOR _186_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_157_)
  );
  NOT _187_ (
    .A(_157_),
    .Y(_158_)
  );
  NOR _188_ (
    .A(state[8]),
    .B(_158_),
    .Y(_159_)
  );
  NAND _189_ (
    .A(_142_),
    .B(_157_),
    .Y(_160_)
  );
  NAND _190_ (
    .A(_155_),
    .B(_159_),
    .Y(_161_)
  );
  NOT _191_ (
    .A(_161_),
    .Y(_162_)
  );
  NOR _192_ (
    .A(state[3]),
    .B(_144_),
    .Y(_163_)
  );
  NAND _193_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  NOT _194_ (
    .A(_164_),
    .Y(_029_)
  );
  NAND _195_ (
    .A(_141_),
    .B(_150_),
    .Y(_165_)
  );
  NOR _196_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_166_)
  );
  NOT _197_ (
    .A(_166_),
    .Y(_167_)
  );
  NOR _198_ (
    .A(state[8]),
    .B(_167_),
    .Y(_168_)
  );
  NOT _199_ (
    .A(_168_),
    .Y(_169_)
  );
  NOR _200_ (
    .A(_160_),
    .B(_167_),
    .Y(_003_)
  );
  NOT _201_ (
    .A(_003_),
    .Y(_004_)
  );
  NOR _202_ (
    .A(state[6]),
    .B(_148_),
    .Y(_005_)
  );
  NAND _203_ (
    .A(_151_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _204_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _205_ (
    .A(_147_),
    .B(state[7]),
    .Y(_008_)
  );
  NAND _206_ (
    .A(state[6]),
    .B(_148_),
    .Y(_009_)
  );
  NOR _207_ (
    .A(_152_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _208_ (
    .A(_151_),
    .B(_008_),
    .Y(_011_)
  );
  NOR _209_ (
    .A(_145_),
    .B(state[4]),
    .Y(_012_)
  );
  NAND _210_ (
    .A(state[5]),
    .B(_153_),
    .Y(_013_)
  );
  NOR _211_ (
    .A(state[4]),
    .B(_013_),
    .Y(_014_)
  );
  NAND _212_ (
    .A(_153_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _213_ (
    .A(_010_),
    .B(_014_),
    .Y(_016_)
  );
  NAND _214_ (
    .A(_011_),
    .B(_015_),
    .Y(_017_)
  );
  NOR _215_ (
    .A(state[5]),
    .B(_146_),
    .Y(_018_)
  );
  NAND _216_ (
    .A(state[4]),
    .B(_153_),
    .Y(_019_)
  );
  NOR _217_ (
    .A(state[5]),
    .B(_019_),
    .Y(_020_)
  );
  NAND _218_ (
    .A(_153_),
    .B(_018_),
    .Y(_021_)
  );
  NOR _219_ (
    .A(_017_),
    .B(_020_),
    .Y(_022_)
  );
  NAND _220_ (
    .A(_016_),
    .B(_021_),
    .Y(_023_)
  );
  NAND _221_ (
    .A(_003_),
    .B(_017_),
    .Y(_024_)
  );
  NOR _222_ (
    .A(_004_),
    .B(_022_),
    .Y(_025_)
  );
  NAND _223_ (
    .A(_003_),
    .B(_023_),
    .Y(_026_)
  );
  NOR _224_ (
    .A(_029_),
    .B(_007_),
    .Y(_027_)
  );
  NOT _225_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _226_ (
    .A(_025_),
    .B(_028_),
    .Y(_030_)
  );
  NAND _227_ (
    .A(_026_),
    .B(_027_),
    .Y(_031_)
  );
  NOR _228_ (
    .A(_156_),
    .B(_169_),
    .Y(_032_)
  );
  NAND _229_ (
    .A(_155_),
    .B(_168_),
    .Y(_033_)
  );
  NOR _230_ (
    .A(_141_),
    .B(state[1]),
    .Y(_034_)
  );
  NAND _231_ (
    .A(_032_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _232_ (
    .A(state[3]),
    .B(_144_),
    .Y(_036_)
  );
  NOR _233_ (
    .A(_161_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _234_ (
    .A(state[0]),
    .B(_143_),
    .Y(_038_)
  );
  NAND _235_ (
    .A(_141_),
    .B(state[1]),
    .Y(_039_)
  );
  NOR _236_ (
    .A(_033_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _237_ (
    .A(_032_),
    .B(_038_),
    .Y(_041_)
  );
  NOR _238_ (
    .A(_037_),
    .B(_040_),
    .Y(_042_)
  );
  NAND _239_ (
    .A(_035_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _240_ (
    .A(_035_),
    .B(_041_),
    .Y(_044_)
  );
  NOR _241_ (
    .A(_037_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _242_ (
    .A(_031_),
    .B(_043_),
    .Y(_046_)
  );
  NAND _243_ (
    .A(_030_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _244_ (
    .A(state[0]),
    .B(_046_),
    .Y(_048_)
  );
  NAND _245_ (
    .A(_165_),
    .B(_007_),
    .Y(_049_)
  );
  NAND _246_ (
    .A(_048_),
    .B(_049_),
    .Y(nxtState[0])
  );
  NOT _247_ (
    .A(nxtState[0]),
    .Y(_050_)
  );
  NOR _248_ (
    .A(_143_),
    .B(_047_),
    .Y(_051_)
  );
  NOT _249_ (
    .A(_051_),
    .Y(_052_)
  );
  NAND _250_ (
    .A(_035_),
    .B(_052_),
    .Y(nxtState[1])
  );
  NOR _251_ (
    .A(FIFOempty0),
    .B(FIFOempty1),
    .Y(_053_)
  );
  NOR _252_ (
    .A(FIFOempty2),
    .B(FIFOempty3),
    .Y(_054_)
  );
  NAND _253_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOT _254_ (
    .A(_055_),
    .Y(_000_)
  );
  NOR _255_ (
    .A(_164_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _256_ (
    .A(_029_),
    .B(_000_),
    .Y(_057_)
  );
  NOR _257_ (
    .A(_046_),
    .B(_056_),
    .Y(_058_)
  );
  NAND _258_ (
    .A(_047_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _259_ (
    .A(state[2]),
    .B(_059_),
    .Y(_060_)
  );
  NAND _260_ (
    .A(_041_),
    .B(_060_),
    .Y(nxtState[2])
  );
  NOT _261_ (
    .A(nxtState[2]),
    .Y(_061_)
  );
  NOR _262_ (
    .A(FIFOcontinue0),
    .B(FIFOcontinue1),
    .Y(_062_)
  );
  NOR _263_ (
    .A(FIFOcontinue2),
    .B(FIFOcontinue3),
    .Y(_063_)
  );
  NAND _264_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _265_ (
    .A(_055_),
    .B(_064_),
    .Y(_065_)
  );
  NOT _266_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _267_ (
    .A(FIFOerror0),
    .B(FIFOerror1),
    .Y(_067_)
  );
  NOT _268_ (
    .A(_067_),
    .Y(_068_)
  );
  NOR _269_ (
    .A(FIFOerror2),
    .B(FIFOerror3),
    .Y(_069_)
  );
  NOT _270_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR _271_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _272_ (
    .A(_037_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _273_ (
    .A(FIFOpause0),
    .B(FIFOpause1),
    .Y(_073_)
  );
  NOR _274_ (
    .A(FIFOpause2),
    .B(FIFOpause3),
    .Y(_074_)
  );
  NAND _275_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _276_ (
    .A(FIFOfull0),
    .B(FIFOfull1),
    .Y(_076_)
  );
  NOR _277_ (
    .A(FIFOfull2),
    .B(FIFOfull3),
    .Y(_077_)
  );
  NAND _278_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _279_ (
    .A(_075_),
    .B(_078_),
    .Y(_079_)
  );
  NOT _280_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _281_ (
    .A(_072_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _282_ (
    .A(_065_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _283_ (
    .A(_066_),
    .B(_080_),
    .Y(_083_)
  );
  NAND _284_ (
    .A(_047_),
    .B(_082_),
    .Y(_084_)
  );
  NAND _285_ (
    .A(state[3]),
    .B(_084_),
    .Y(_085_)
  );
  NOR _286_ (
    .A(_164_),
    .B(_000_),
    .Y(_086_)
  );
  NOR _287_ (
    .A(_025_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _288_ (
    .A(_085_),
    .B(_087_),
    .Y(nxtState[3])
  );
  NOT _289_ (
    .A(nxtState[3]),
    .Y(_088_)
  );
  NOR _290_ (
    .A(_066_),
    .B(_072_),
    .Y(_089_)
  );
  NAND _291_ (
    .A(_150_),
    .B(_007_),
    .Y(_090_)
  );
  NAND _292_ (
    .A(_047_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _293_ (
    .A(_058_),
    .B(_090_),
    .Y(_092_)
  );
  NAND _294_ (
    .A(state[4]),
    .B(_092_),
    .Y(_093_)
  );
  NAND _295_ (
    .A(_080_),
    .B(_089_),
    .Y(_094_)
  );
  NAND _296_ (
    .A(_093_),
    .B(_094_),
    .Y(nxtState[4])
  );
  NOT _297_ (
    .A(nxtState[4]),
    .Y(_095_)
  );
  NAND _298_ (
    .A(state[5]),
    .B(_092_),
    .Y(_096_)
  );
  NAND _299_ (
    .A(_066_),
    .B(_081_),
    .Y(_097_)
  );
  NAND _300_ (
    .A(_096_),
    .B(_097_),
    .Y(nxtState[5])
  );
  NOT _301_ (
    .A(nxtState[5]),
    .Y(_098_)
  );
  NAND _302_ (
    .A(state[6]),
    .B(_084_),
    .Y(_099_)
  );
  NOR _303_ (
    .A(_072_),
    .B(_079_),
    .Y(_100_)
  );
  NAND _304_ (
    .A(_066_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _305_ (
    .A(_099_),
    .B(_101_),
    .Y(nxtState[6])
  );
  NOT _306_ (
    .A(nxtState[6]),
    .Y(_102_)
  );
  NAND _307_ (
    .A(state[7]),
    .B(_091_),
    .Y(_103_)
  );
  NAND _308_ (
    .A(state[7]),
    .B(_083_),
    .Y(_104_)
  );
  NAND _309_ (
    .A(_071_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _310_ (
    .A(_037_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _311_ (
    .A(_103_),
    .B(_106_),
    .Y(nxtState[7])
  );
  NOT _312_ (
    .A(nxtState[7]),
    .Y(_107_)
  );
  NOR _313_ (
    .A(_149_),
    .B(reset),
    .Y(_108_)
  );
  NOT _314_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _315_ (
    .A(_050_),
    .B(_108_),
    .Y(_001_[0])
  );
  NOR _316_ (
    .A(nxtState[1]),
    .B(_108_),
    .Y(_110_)
  );
  NOT _317_ (
    .A(_110_),
    .Y(_001_[1])
  );
  NOR _318_ (
    .A(_061_),
    .B(_108_),
    .Y(_001_[2])
  );
  NOR _319_ (
    .A(_088_),
    .B(_108_),
    .Y(_001_[3])
  );
  NOR _320_ (
    .A(_095_),
    .B(_108_),
    .Y(_001_[4])
  );
  NOR _321_ (
    .A(_098_),
    .B(_108_),
    .Y(_001_[5])
  );
  NOR _322_ (
    .A(_102_),
    .B(_108_),
    .Y(_001_[6])
  );
  NOR _323_ (
    .A(_107_),
    .B(_108_),
    .Y(_001_[7])
  );
  NOR _324_ (
    .A(_142_),
    .B(_108_),
    .Y(_001_[8])
  );
  NOR _325_ (
    .A(init),
    .B(reset),
    .Y(_111_)
  );
  NOT _326_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _327_ (
    .A(nxtState[0]),
    .B(_112_),
    .Y(_113_)
  );
  NOR _328_ (
    .A(state[0]),
    .B(_109_),
    .Y(_114_)
  );
  NOR _329_ (
    .A(_113_),
    .B(_114_),
    .Y(_002_[0])
  );
  NAND _330_ (
    .A(state[1]),
    .B(_108_),
    .Y(_115_)
  );
  NAND _331_ (
    .A(nxtState[1]),
    .B(_111_),
    .Y(_116_)
  );
  NAND _332_ (
    .A(_115_),
    .B(_116_),
    .Y(_002_[1])
  );
  NAND _333_ (
    .A(state[2]),
    .B(_108_),
    .Y(_117_)
  );
  NAND _334_ (
    .A(nxtState[2]),
    .B(_111_),
    .Y(_118_)
  );
  NAND _335_ (
    .A(_117_),
    .B(_118_),
    .Y(_002_[2])
  );
  NAND _336_ (
    .A(state[3]),
    .B(_108_),
    .Y(_119_)
  );
  NAND _337_ (
    .A(nxtState[3]),
    .B(_111_),
    .Y(_120_)
  );
  NAND _338_ (
    .A(_119_),
    .B(_120_),
    .Y(_002_[3])
  );
  NAND _339_ (
    .A(nxtState[4]),
    .B(_111_),
    .Y(_121_)
  );
  NAND _340_ (
    .A(state[4]),
    .B(_108_),
    .Y(_122_)
  );
  NAND _341_ (
    .A(_121_),
    .B(_122_),
    .Y(_002_[4])
  );
  NAND _342_ (
    .A(state[5]),
    .B(_108_),
    .Y(_123_)
  );
  NAND _343_ (
    .A(nxtState[5]),
    .B(_111_),
    .Y(_124_)
  );
  NAND _344_ (
    .A(_123_),
    .B(_124_),
    .Y(_002_[5])
  );
  NAND _345_ (
    .A(state[6]),
    .B(_108_),
    .Y(_125_)
  );
  NAND _346_ (
    .A(nxtState[6]),
    .B(_111_),
    .Y(_126_)
  );
  NAND _347_ (
    .A(_125_),
    .B(_126_),
    .Y(_002_[6])
  );
  NAND _348_ (
    .A(state[7]),
    .B(_108_),
    .Y(_127_)
  );
  NAND _349_ (
    .A(nxtState[7]),
    .B(_111_),
    .Y(_128_)
  );
  NAND _350_ (
    .A(_127_),
    .B(_128_),
    .Y(_002_[7])
  );
  NOR _351_ (
    .A(_142_),
    .B(reset),
    .Y(_002_[8])
  );
  NAND _352_ (
    .A(FIFOerror0),
    .B(_007_),
    .Y(_129_)
  );
  NOT _353_ (
    .A(_129_),
    .Y(_135_)
  );
  NAND _354_ (
    .A(FIFOerror1),
    .B(_007_),
    .Y(_130_)
  );
  NOT _355_ (
    .A(_130_),
    .Y(_136_)
  );
  NAND _356_ (
    .A(FIFOerror2),
    .B(_007_),
    .Y(_131_)
  );
  NOT _357_ (
    .A(_131_),
    .Y(_137_)
  );
  NAND _358_ (
    .A(FIFOerror3),
    .B(_007_),
    .Y(_132_)
  );
  NOT _359_ (
    .A(_132_),
    .Y(_138_)
  );
  NAND _360_ (
    .A(_011_),
    .B(_021_),
    .Y(_133_)
  );
  NAND _361_ (
    .A(_003_),
    .B(_133_),
    .Y(_134_)
  );
  NOR _362_ (
    .A(_079_),
    .B(_134_),
    .Y(_139_)
  );
  NOR _363_ (
    .A(_024_),
    .B(_065_),
    .Y(_140_)
  );
  BUF _364_ (
    .A(state[8]),
    .Y(nxtState[8])
  );
  DFF _365_ (
    .C(clk),
    .D(_002_[0]),
    .Q(state[0])
  );
  DFF _366_ (
    .C(clk),
    .D(_002_[1]),
    .Q(state[1])
  );
  DFF _367_ (
    .C(clk),
    .D(_002_[2]),
    .Q(state[2])
  );
  DFF _368_ (
    .C(clk),
    .D(_002_[3]),
    .Q(state[3])
  );
  DFF _369_ (
    .C(clk),
    .D(_002_[4]),
    .Q(state[4])
  );
  DFF _370_ (
    .C(clk),
    .D(_002_[5]),
    .Q(state[5])
  );
  DFF _371_ (
    .C(clk),
    .D(_002_[6]),
    .Q(state[6])
  );
  DFF _372_ (
    .C(clk),
    .D(_002_[7]),
    .Q(state[7])
  );
  DFF _373_ (
    .C(clk),
    .D(_002_[8]),
    .Q(state[8])
  );
  DFF _374_ (
    .C(clk),
    .D(_001_[0]),
    .Q(nxtState[0])
  );
  DFF _375_ (
    .C(clk),
    .D(_001_[1]),
    .Q(nxtState[1])
  );
  DFF _376_ (
    .C(clk),
    .D(_001_[2]),
    .Q(nxtState[2])
  );
  DFF _377_ (
    .C(clk),
    .D(_001_[3]),
    .Q(nxtState[3])
  );
  DFF _378_ (
    .C(clk),
    .D(_001_[4]),
    .Q(nxtState[4])
  );
  DFF _379_ (
    .C(clk),
    .D(_001_[5]),
    .Q(nxtState[5])
  );
  DFF _380_ (
    .C(clk),
    .D(_001_[6]),
    .Q(nxtState[6])
  );
  DFF _381_ (
    .C(clk),
    .D(_001_[7]),
    .Q(nxtState[7])
  );
  DFF _382_ (
    .C(clk),
    .D(_001_[8]),
    .Q(nxtState[8])
  );
  \$_DLATCH_P_  _383_ (
    .D(1'h1),
    .E(_135_),
    .Q(error_full[0])
  );
  \$_DLATCH_P_  _384_ (
    .D(1'h1),
    .E(_136_),
    .Q(error_full[1])
  );
  \$_DLATCH_P_  _385_ (
    .D(1'h1),
    .E(_137_),
    .Q(error_full[2])
  );
  \$_DLATCH_P_  _386_ (
    .D(1'h1),
    .E(_138_),
    .Q(error_full[3])
  );
  \$_DLATCH_P_  _387_ (
    .D(1'h1),
    .E(_139_),
    .Q(pause[0])
  );
  \$_DLATCH_P_  _388_ (
    .D(1'h1),
    .E(1'h0),
    .Q(pause[1])
  );
  \$_DLATCH_P_  _389_ (
    .D(1'h1),
    .E(_140_),
    .Q(continue[0])
  );
  \$_DLATCH_P_  _390_ (
    .D(1'h1),
    .E(1'h0),
    .Q(continue[1])
  );
  \$_DLATCH_P_  _391_ (
    .D(_000_),
    .E(_029_),
    .Q(idle)
  );
  assign FIFOcontinue = { FIFOcontinue3, FIFOcontinue2, FIFOcontinue1, FIFOcontinue0 };
  assign FIFOempty = { FIFOempty3, FIFOempty2, FIFOempty1, FIFOempty0 };
  assign FIFOerror = { FIFOerror3, FIFOerror2, FIFOerror1, FIFOerror0 };
  assign FIFOfull = { FIFOfull3, FIFOfull2, FIFOfull1, FIFOfull0 };
  assign FIFOpause = { FIFOpause3, FIFOpause2, FIFOpause1, FIFOpause0 };
  assign continue[3:2] = { continue[1], continue[1] };
  assign pause[3:2] = { pause[1], pause[1] };
endmodule
