/* Generated by Yosys 0.7+281 (git sha1 d38a64b, gcc 4.9.2-10 -fPIC -Os) */

(* top =  1  *)
(* src = "fsm.v:5" *)
module fsm(clk, reset, init, FIFOpause0, FIFOpause1, FIFOpause2, FIFOpause3, FIFOcontinue0, FIFOcontinue1, FIFOcontinue2, FIFOcontinue3, FIFOempty0, FIFOempty1, FIFOempty2, FIFOempty3, FIFOerror0, FIFOerror1, FIFOerror2, FIFOerror3, FIFOfull0, FIFOfull1, FIFOfull2, FIFOfull3, error_full, pause, continue, idle);
  (* src = "fsm.v:109" *)
  wire _000_;
  (* src = "fsm.v:97" *)
  wire [8:0] _001_;
  (* src = "fsm.v:97" *)
  wire [8:0] _002_;
  (* src = "fsm.v:109" *)
  wire [8:0] _003_;
  (* src = "fsm.v:109" *)
  wire [8:0] _004_;
  (* src = "fsm.v:109" *)
  wire [8:0] _005_;
  (* src = "fsm.v:109" *)
  wire [8:0] _006_;
  (* src = "fsm.v:109" *)
  wire [8:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire [3:0] _057_;
  wire [1:0] _058_;
  wire _059_;
  wire [3:0] _060_;
  wire [1:0] _061_;
  wire _062_;
  wire [3:0] _063_;
  wire [1:0] _064_;
  wire _065_;
  wire [3:0] _066_;
  wire [1:0] _067_;
  wire _068_;
  wire [3:0] _069_;
  wire [1:0] _070_;
  wire _071_;
  wire [3:0] _072_;
  wire [1:0] _073_;
  wire _074_;
  wire [3:0] _075_;
  wire [1:0] _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire [2:0] _083_;
  wire _084_;
  wire [2:0] _085_;
  wire _086_;
  wire [2:0] _087_;
  wire _088_;
  wire [2:0] _089_;
  wire _090_;
  wire [2:0] _091_;
  wire _092_;
  wire [2:0] _093_;
  wire _094_;
  wire [2:0] _095_;
  wire _096_;
  wire [2:0] _097_;
  wire _098_;
  wire [2:0] _099_;
  wire _100_;
  wire [2:0] _101_;
  wire _102_;
  wire [1:0] _103_;
  wire [1:0] _104_;
  wire [3:0] _105_;
  wire [1:0] _106_;
  wire _107_;
  wire [1:0] _108_;
  wire _109_;
  wire [1:0] _110_;
  wire _111_;
  wire _112_;
  wire [1:0] _113_;
  wire _114_;
  wire [8:0] _115_;
  wire [8:0] _116_;
  wire [8:0] _117_;
  wire [8:0] _118_;
  wire [8:0] _119_;
  wire [8:0] _120_;
  wire [8:0] _121_;
  wire [8:0] _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  (* src = "fsm.v:132" *)
  wire _127_;
  (* src = "fsm.v:140" *)
  wire _128_;
  (* src = "fsm.v:144" *)
  wire _129_;
  (* src = "fsm.v:148" *)
  wire _130_;
  wire _131_;
  wire _132_;
  wire [8:0] _133_;
  (* src = "fsm.v:113|<techmap.v>:432" *)
  wire [53:0] _134_;
  (* src = "fsm.v:113|<techmap.v>:428" *)
  wire [8:0] _135_;
  wire [8:0] _136_;
  wire [8:0] _137_;
  (* src = "fsm.v:113|<techmap.v>:445" *)
  wire _138_;
  (* src = "fsm.v:61" *)
  wire [3:0] FIFOcontinue;
  (* src = "fsm.v:20" *)
  input FIFOcontinue0;
  (* src = "fsm.v:21" *)
  input FIFOcontinue1;
  (* src = "fsm.v:22" *)
  input FIFOcontinue2;
  (* src = "fsm.v:23" *)
  input FIFOcontinue3;
  (* src = "fsm.v:66" *)
  wire [3:0] FIFOcontinueOR;
  (* src = "fsm.v:62" *)
  wire [3:0] FIFOempty;
  (* src = "fsm.v:24" *)
  input FIFOempty0;
  (* src = "fsm.v:25" *)
  input FIFOempty1;
  (* src = "fsm.v:26" *)
  input FIFOempty2;
  (* src = "fsm.v:27" *)
  input FIFOempty3;
  (* src = "fsm.v:64" *)
  wire [3:0] FIFOerror;
  (* src = "fsm.v:28" *)
  input FIFOerror0;
  (* src = "fsm.v:29" *)
  input FIFOerror1;
  (* src = "fsm.v:30" *)
  input FIFOerror2;
  (* src = "fsm.v:31" *)
  input FIFOerror3;
  (* src = "fsm.v:63" *)
  wire [3:0] FIFOfull;
  (* src = "fsm.v:32" *)
  input FIFOfull0;
  (* src = "fsm.v:33" *)
  input FIFOfull1;
  (* src = "fsm.v:34" *)
  input FIFOfull2;
  (* src = "fsm.v:35" *)
  input FIFOfull3;
  (* src = "fsm.v:60" *)
  wire [3:0] FIFOpause;
  (* src = "fsm.v:16" *)
  input FIFOpause0;
  (* src = "fsm.v:17" *)
  input FIFOpause1;
  (* src = "fsm.v:18" *)
  input FIFOpause2;
  (* src = "fsm.v:19" *)
  input FIFOpause3;
  (* src = "fsm.v:65" *)
  wire [3:0] FIFOpauseOR;
  (* src = "fsm.v:13" *)
  input clk;
  (* src = "fsm.v:39" *)
  output [3:0] continue;
  (* src = "fsm.v:37" *)
  output [3:0] error_full;
  (* src = "fsm.v:40" *)
  output idle;
  (* src = "fsm.v:15" *)
  input init;
  (* src = "fsm.v:47" *)
  reg [8:0] nxtState;
  (* src = "fsm.v:38" *)
  output [3:0] pause;
  (* src = "fsm.v:14" *)
  input reset;
  (* src = "fsm.v:47" *)
  reg [8:0] state;
  assign _009_ = _107_ |(* src = "fsm.v:113" *)  state[8];
  assign _057_[0] = state[0] |(* src = "fsm.v:113" *)  _115_[1];
  assign _058_[0] = _057_[0] |(* src = "fsm.v:113" *)  _057_[1];
  assign _059_ = _058_[0] |(* src = "fsm.v:113" *)  _058_[1];
  assign _123_ = _059_ |(* src = "fsm.v:113" *)  state[8];
  assign _060_[0] = _116_[0] |(* src = "fsm.v:113" *)  state[1];
  assign _061_[0] = _060_[0] |(* src = "fsm.v:113" *)  _057_[1];
  assign _062_ = _061_[0] |(* src = "fsm.v:113" *)  _058_[1];
  assign _124_ = _062_ |(* src = "fsm.v:113" *)  state[8];
  assign _063_[1] = _117_[2] |(* src = "fsm.v:113" *)  state[3];
  assign _064_[0] = _063_[0] |(* src = "fsm.v:113" *)  _063_[1];
  assign _058_[1] = _057_[2] |(* src = "fsm.v:113" *)  _057_[3];
  assign _065_ = _064_[0] |(* src = "fsm.v:113" *)  _058_[1];
  assign _125_ = _065_ |(* src = "fsm.v:113" *)  state[8];
  assign _057_[1] = state[2] |(* src = "fsm.v:113" *)  state[3];
  assign _066_[2] = _118_[4] |(* src = "fsm.v:113" *)  state[5];
  assign _067_[1] = _066_[2] |(* src = "fsm.v:113" *)  _057_[3];
  assign _068_ = _067_[0] |(* src = "fsm.v:113" *)  _067_[1];
  assign _018_ = _068_ |(* src = "fsm.v:113" *)  state[8];
  assign _063_[0] = state[0] |(* src = "fsm.v:113" *)  state[1];
  assign _069_[1] = state[2] |(* src = "fsm.v:113" *)  _119_[3];
  assign _057_[2] = state[4] |(* src = "fsm.v:113" *)  state[5];
  assign _057_[3] = state[6] |(* src = "fsm.v:113" *)  state[7];
  assign _070_[0] = _063_[0] |(* src = "fsm.v:113" *)  _069_[1];
  assign _071_ = _070_[0] |(* src = "fsm.v:113" *)  _058_[1];
  assign _126_ = _071_ |(* src = "fsm.v:113" *)  state[8];
  assign _072_[3] = _120_[6] |(* src = "fsm.v:113" *)  state[7];
  assign _073_[1] = _057_[2] |(* src = "fsm.v:113" *)  _072_[3];
  assign _074_ = _067_[0] |(* src = "fsm.v:113" *)  _073_[1];
  assign _019_ = _074_ |(* src = "fsm.v:113" *)  state[8];
  assign _075_[2] = state[4] |(* src = "fsm.v:113" *)  _121_[5];
  assign _076_[1] = _075_[2] |(* src = "fsm.v:113" *)  _057_[3];
  assign _077_ = _067_[0] |(* src = "fsm.v:113" *)  _076_[1];
  assign _023_ = _077_ |(* src = "fsm.v:113" *)  state[8];
  assign _029_ = _047_ | _009_;
  assign _031_ = _048_ | _009_;
  assign _033_ = _049_ | _009_;
  assign _035_ = _050_ | _009_;
  assign _078_ = _053_ | _052_;
  assign _038_ = _078_ | _051_;
  assign _041_ = _079_ | _051_;
  assign _079_ = _040_ | _039_;
  assign _080_ = _056_ | _055_;
  assign _044_ = _080_ | _054_;
  assign _081_ = _045_ | _039_;
  assign _046_ = _081_ | _054_;
  assign _082_ = _040_ | _045_;
  assign _008_ = _082_ | _039_;
  assign _083_[1] = _134_[25] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[34];
  assign _084_ = _083_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _083_[1];
  assign _085_[1] = _134_[26] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[35];
  assign _086_ = _085_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _085_[1];
  assign _087_[1] = _134_[24] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[33];
  assign _088_ = _087_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _087_[1];
  assign _089_[1] = _134_[22] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[31];
  assign _090_ = _089_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _089_[1];
  assign _091_[0] = _134_[3] |(* src = "fsm.v:113|<techmap.v>:441" *)  _008_;
  assign _091_[1] = _134_[21] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[30];
  assign _092_ = _091_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _091_[1];
  assign _093_[1] = _134_[20] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[29];
  assign _094_ = _093_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _093_[1];
  assign _135_[2] = _094_ |(* src = "fsm.v:113|<techmap.v>:441" *)  _093_[2];
  assign _095_[1] = _134_[19] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[28];
  assign _096_ = _095_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _095_[1];
  assign _135_[1] = _096_ |(* src = "fsm.v:113|<techmap.v>:441" *)  _095_[2];
  assign _097_[1] = _134_[18] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[27];
  assign _098_ = _097_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _097_[1];
  assign _099_[0] = _131_ |(* src = "fsm.v:113|<techmap.v>:445" *)  _008_;
  assign _099_[1] = _132_ |(* src = "fsm.v:113|<techmap.v>:445" *)  _027_;
  assign _099_[2] = _093_[2] |(* src = "fsm.v:113|<techmap.v>:445" *)  _095_[2];
  assign _100_ = _099_[0] |(* src = "fsm.v:113|<techmap.v>:445" *)  _099_[1];
  assign _138_ = _100_ |(* src = "fsm.v:113|<techmap.v>:445" *)  _099_[2];
  assign _101_[1] = _134_[23] |(* src = "fsm.v:113|<techmap.v>:441" *)  _134_[32];
  assign _102_ = _101_[0] |(* src = "fsm.v:113|<techmap.v>:441" *)  _101_[1];
  assign _103_[0] = FIFOempty0 |(* src = "fsm.v:125" *)  FIFOempty1;
  assign _112_ = _103_[0] |(* src = "fsm.v:125" *)  _103_[1];
  assign _104_[0] = FIFOerror0 |(* src = "fsm.v:148" *)  FIFOerror1;
  assign _104_[1] = FIFOerror2 |(* src = "fsm.v:148" *)  FIFOerror3;
  assign _130_ = _104_[0] |(* src = "fsm.v:148" *)  _104_[1];
  assign _105_[3] = state[6] |(* src = "fsm.v:113" *)  _122_[7];
  assign _067_[0] = _063_[0] |(* src = "fsm.v:113" *)  _057_[1];
  assign _106_[1] = _057_[2] |(* src = "fsm.v:113" *)  _105_[3];
  assign _107_ = _067_[0] |(* src = "fsm.v:113" *)  _106_[1];
  assign _108_[0] = FIFOfull0 |(* src = "fsm.v:94" *)  FIFOfull1;
  assign _108_[1] = FIFOfull2 |(* src = "fsm.v:94" *)  FIFOfull3;
  assign _109_ = _108_[0] |(* src = "fsm.v:94" *)  _108_[1];
  assign _110_[0] = FIFOpause0 |(* src = "fsm.v:94" *)  FIFOpause1;
  assign _110_[1] = FIFOpause2 |(* src = "fsm.v:94" *)  FIFOpause3;
  assign _111_ = _110_[0] |(* src = "fsm.v:94" *)  _110_[1];
  assign _103_[1] = FIFOempty2 |(* src = "fsm.v:95" *)  FIFOempty3;
  assign _113_[0] = FIFOcontinue0 |(* src = "fsm.v:95" *)  FIFOcontinue1;
  assign _113_[1] = FIFOcontinue2 |(* src = "fsm.v:95" *)  FIFOcontinue3;
  assign _114_ = _113_[0] |(* src = "fsm.v:95" *)  _113_[1];
  assign _131_ = ~(* src = "fsm.v:113" *) _009_;
  assign _093_[2] = ~(* src = "fsm.v:113" *) _123_;
  assign _095_[2] = ~(* src = "fsm.v:113" *) _124_;
  assign _027_ = ~(* src = "fsm.v:113" *) _125_;
  assign _040_ = ~(* src = "fsm.v:113" *) _018_;
  assign _132_ = ~(* src = "fsm.v:113" *) _126_;
  assign _039_ = ~(* src = "fsm.v:113" *) _019_;
  assign _045_ = ~(* src = "fsm.v:113" *) _023_;
  assign FIFOpauseOR[0] = _109_ |(* src = "fsm.v:94" *)  _111_;
  assign FIFOcontinueOR[0] = _112_ |(* src = "fsm.v:95" *)  _114_;
  assign _127_ = FIFOpauseOR[0] &(* src = "fsm.v:132" *)  _024_;
  assign _128_ = FIFOcontinueOR[0] &(* src = "fsm.v:140" *)  _020_;
  assign _129_ = FIFOpauseOR[0] &(* src = "fsm.v:144" *)  FIFOcontinueOR[0];
  assign _007_[0] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[0];
  assign _007_[1] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[1];
  assign _007_[2] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[2];
  assign _007_[3] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[3];
  assign _007_[4] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[4];
  assign _007_[5] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[5];
  assign _007_[6] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[6];
  assign _007_[7] = _130_ ? (* src = "fsm.v:148" *) 1'h1 : _006_[7];
  assign _007_[8] = _130_ ? (* src = "fsm.v:148" *) 1'h0 : _006_[8];
  assign _136_[0] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[0];
  assign _136_[1] = init ? (* src = "fsm.v:101" *) 1'h1 : nxtState[1];
  assign _136_[2] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[2];
  assign _136_[3] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[3];
  assign _136_[4] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[4];
  assign _136_[5] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[5];
  assign _136_[6] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[6];
  assign _136_[7] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[7];
  assign _136_[8] = init ? (* src = "fsm.v:101" *) 1'h0 : nxtState[8];
  assign _001_[0] = reset ? (* src = "fsm.v:98" *) nxtState[0] : _136_[0];
  assign _001_[1] = reset ? (* src = "fsm.v:98" *) nxtState[1] : _136_[1];
  assign _001_[2] = reset ? (* src = "fsm.v:98" *) nxtState[2] : _136_[2];
  assign _001_[3] = reset ? (* src = "fsm.v:98" *) nxtState[3] : _136_[3];
  assign _001_[4] = reset ? (* src = "fsm.v:98" *) nxtState[4] : _136_[4];
  assign _001_[5] = reset ? (* src = "fsm.v:98" *) nxtState[5] : _136_[5];
  assign _001_[6] = reset ? (* src = "fsm.v:98" *) nxtState[6] : _136_[6];
  assign _001_[7] = reset ? (* src = "fsm.v:98" *) nxtState[7] : _136_[7];
  assign _001_[8] = reset ? (* src = "fsm.v:98" *) nxtState[8] : _136_[8];
  assign _137_[0] = init ? (* src = "fsm.v:101" *) state[0] : nxtState[0];
  assign _137_[1] = init ? (* src = "fsm.v:101" *) state[1] : nxtState[1];
  assign _137_[2] = init ? (* src = "fsm.v:101" *) state[2] : nxtState[2];
  assign _137_[3] = init ? (* src = "fsm.v:101" *) state[3] : nxtState[3];
  assign _137_[4] = init ? (* src = "fsm.v:101" *) state[4] : nxtState[4];
  assign _137_[5] = init ? (* src = "fsm.v:101" *) state[5] : nxtState[5];
  assign _137_[6] = init ? (* src = "fsm.v:101" *) state[6] : nxtState[6];
  assign _137_[7] = init ? (* src = "fsm.v:101" *) state[7] : nxtState[7];
  assign _137_[8] = init ? (* src = "fsm.v:101" *) state[8] : nxtState[8];
  assign _002_[0] = reset ? (* src = "fsm.v:98" *) 1'h1 : _137_[0];
  assign _002_[1] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[1];
  assign _002_[2] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[2];
  assign _002_[3] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[3];
  assign _002_[4] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[4];
  assign _002_[5] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[5];
  assign _002_[6] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[6];
  assign _002_[7] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[7];
  assign _002_[8] = reset ? (* src = "fsm.v:98" *) 1'h0 : _137_[8];
  assign nxtState[0] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _098_ : state[0];
  assign nxtState[1] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _135_[1] : state[1];
  assign nxtState[2] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _135_[2] : state[2];
  assign nxtState[3] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _092_ : state[3];
  assign nxtState[4] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _090_ : state[4];
  assign nxtState[5] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _102_ : state[5];
  assign nxtState[6] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _088_ : state[6];
  assign nxtState[7] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _084_ : state[7];
  assign nxtState[8] = _138_ ? (* src = "fsm.v:113|<techmap.v>:445" *) _086_ : state[8];
  assign _006_[0] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[0];
  assign _006_[1] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[1];
  assign _006_[2] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[2];
  assign _006_[3] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[3];
  assign _006_[4] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[4];
  assign _006_[5] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[5];
  assign _006_[6] = _129_ ? (* src = "fsm.v:144" *) 1'h1 : _005_[6];
  assign _006_[7] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[7];
  assign _006_[8] = _129_ ? (* src = "fsm.v:144" *) 1'h0 : _005_[8];
  assign _005_[0] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[0];
  assign _005_[1] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[1];
  assign _005_[2] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[2];
  assign _005_[3] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[3];
  assign _005_[4] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[4];
  assign _005_[5] = _128_ ? (* src = "fsm.v:140" *) 1'h1 : _004_[5];
  assign _005_[6] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[6];
  assign _005_[7] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[7];
  assign _005_[8] = _128_ ? (* src = "fsm.v:140" *) 1'h0 : _004_[8];
  assign _004_[0] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[0];
  assign _004_[1] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[1];
  assign _004_[2] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[2];
  assign _004_[3] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[3];
  assign _004_[4] = _127_ ? (* src = "fsm.v:132" *) 1'h1 : state[4];
  assign _004_[5] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[5];
  assign _004_[6] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[6];
  assign _004_[7] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[7];
  assign _004_[8] = _127_ ? (* src = "fsm.v:132" *) 1'h0 : state[8];
  assign _003_[0] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[0];
  assign _003_[1] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[1];
  assign _003_[2] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[2];
  assign _003_[3] = _112_ ? (* src = "fsm.v:125" *) 1'h1 : state[3];
  assign _003_[4] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[4];
  assign _003_[5] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[5];
  assign _003_[6] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[6];
  assign _003_[7] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[7];
  assign _003_[8] = _112_ ? (* src = "fsm.v:125" *) 1'h0 : state[8];
  assign _000_ = ~(* src = "fsm.v:125" *) _112_;
  assign _133_[0] = reset ? (* src = "fsm.v:222" *) 1'h1 : state[0];
  assign _133_[1] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[1];
  assign _133_[2] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[2];
  assign _133_[3] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[3];
  assign _133_[4] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[4];
  assign _133_[5] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[5];
  assign _133_[6] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[6];
  assign _133_[7] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[7];
  assign _133_[8] = reset ? (* src = "fsm.v:222" *) 1'h0 : state[8];
  assign _010_ = ~FIFOerror0;
  assign _011_ = ~_029_;
  assign _012_ = ~FIFOerror1;
  assign _013_ = ~_031_;
  assign _014_ = ~FIFOerror2;
  assign _015_ = ~_033_;
  assign _016_ = ~FIFOerror3;
  assign _017_ = ~_035_;
  assign _020_ = ~FIFOpauseOR[0];
  assign _021_ = ~_038_;
  assign _022_ = ~_041_;
  assign _024_ = ~FIFOcontinueOR[0];
  assign _025_ = ~_044_;
  assign _026_ = ~_046_;
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[0] <= _002_[0];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[1] <= _002_[1];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[2] <= _002_[2];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[3] <= _002_[3];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[4] <= _002_[4];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[5] <= _002_[5];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[6] <= _002_[6];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[7] <= _002_[7];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      state[8] <= _002_[8];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[0] <= _001_[0];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[1] <= _001_[1];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[2] <= _001_[2];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[3] <= _001_[3];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[4] <= _001_[4];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[5] <= _001_[5];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[6] <= _001_[6];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[7] <= _001_[7];
  (* src = "fsm.v:97" *)
  always @(posedge clk)
      nxtState[8] <= _001_[8];
  \$_DLATCH_P_  _377_ (
    .D(1'h1),
    .E(_011_),
    .Q(error_full[0])
  );
  \$_DLATCH_P_  _378_ (
    .D(1'h1),
    .E(_013_),
    .Q(error_full[1])
  );
  \$_DLATCH_P_  _379_ (
    .D(1'h1),
    .E(_015_),
    .Q(error_full[2])
  );
  \$_DLATCH_P_  _380_ (
    .D(1'h1),
    .E(_017_),
    .Q(error_full[3])
  );
  \$_DLATCH_P_  _381_ (
    .D(1'h1),
    .E(_021_),
    .Q(pause[0])
  );
  \$_DLATCH_P_  _382_ (
    .D(1'h1),
    .E(_022_),
    .Q(pause[1])
  );
  \$_DLATCH_P_  _383_ (
    .D(1'h1),
    .E(_025_),
    .Q(continue[0])
  );
  \$_DLATCH_P_  _384_ (
    .D(1'h1),
    .E(_026_),
    .Q(continue[1])
  );
  \$_DLATCH_P_  _385_ (
    .D(_000_),
    .E(_027_),
    .Q(idle)
  );
  assign _115_[1] = state[1] ^(* src = "fsm.v:113" *)  1'h1;
  assign _116_[0] = state[0] ^(* src = "fsm.v:113" *)  1'h1;
  assign _117_[2] = state[2] ^(* src = "fsm.v:113" *)  1'h1;
  assign _118_[4] = state[4] ^(* src = "fsm.v:113" *)  1'h1;
  assign _119_[3] = state[3] ^(* src = "fsm.v:113" *)  1'h1;
  assign _120_[6] = state[6] ^(* src = "fsm.v:113" *)  1'h1;
  assign _121_[5] = state[5] ^(* src = "fsm.v:113" *)  1'h1;
  assign _028_ = _131_ & _010_;
  assign _047_ = _131_ & _028_;
  assign _030_ = _131_ & _012_;
  assign _048_ = _131_ & _030_;
  assign _032_ = _131_ & _014_;
  assign _049_ = _131_ & _032_;
  assign _034_ = _131_ & _016_;
  assign _050_ = _131_ & _034_;
  assign _051_ = _018_ & _019_;
  assign _036_ = _039_ & _020_;
  assign _052_ = _039_ & _036_;
  assign _037_ = _040_ & _020_;
  assign _053_ = _040_ & _037_;
  assign _042_ = _039_ & _024_;
  assign _055_ = _039_ & _042_;
  assign _043_ = _045_ & _024_;
  assign _056_ = _045_ & _043_;
  assign _054_ = _023_ & _019_;
  assign _134_[27] = _003_[0] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[28] = _003_[1] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[29] = _003_[2] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[30] = _003_[3] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[31] = _003_[4] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[32] = _003_[5] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[33] = _003_[6] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[34] = _003_[7] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[35] = _003_[8] &(* src = "fsm.v:113|<techmap.v>:434" *)  _027_;
  assign _134_[18] = _007_[0] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[19] = _007_[1] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[20] = _007_[2] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[21] = _007_[3] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[22] = _007_[4] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[23] = _007_[5] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[24] = _007_[6] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[25] = _007_[7] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _134_[26] = _007_[8] &(* src = "fsm.v:113|<techmap.v>:434" *)  _132_;
  assign _097_[0] = _133_[0] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _095_[0] = _133_[1] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _093_[0] = _133_[2] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _134_[3] = _133_[3] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _089_[0] = _133_[4] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _101_[0] = _133_[5] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _087_[0] = _133_[6] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _083_[0] = _133_[7] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _085_[0] = _133_[8] &(* src = "fsm.v:113|<techmap.v>:434" *)  _131_;
  assign _122_[7] = state[7] ^(* src = "fsm.v:113" *)  1'h1;
  assign FIFOcontinue = { FIFOcontinue3, FIFOcontinue2, FIFOcontinue1, FIFOcontinue0 };
  assign FIFOcontinueOR[3:1] = 3'h0;
  assign FIFOempty = { FIFOempty3, FIFOempty2, FIFOempty1, FIFOempty0 };
  assign FIFOerror = { FIFOerror3, FIFOerror2, FIFOerror1, FIFOerror0 };
  assign FIFOfull = { FIFOfull3, FIFOfull2, FIFOfull1, FIFOfull0 };
  assign FIFOpause = { FIFOpause3, FIFOpause2, FIFOpause1, FIFOpause0 };
  assign FIFOpauseOR[3:1] = 3'h0;
  assign continue[3:2] = { continue[1], continue[1] };
  assign pause[3:2] = { pause[1], pause[1] };
endmodule
