/* Generated by Yosys 0.7+281 (git sha1 d38a64b, gcc 4.9.2-10 -fPIC -Os) */

(* top =  1  *)
(* src = "fsm.v:5" *)
module fsm(clk, reset, init, FIFOpause0, FIFOpause1, FIFOpause2, FIFOpause3, FIFOcontinue0, FIFOcontinue1, FIFOcontinue2, FIFOcontinue3, FIFOempty0, FIFOempty1, FIFOempty2, FIFOempty3, FIFOerror0, FIFOerror1, FIFOerror2, FIFOerror3, FIFOfull0, FIFOfull1, FIFOfull2, FIFOfull3, error_full, pause, continue, idle);
  (* src = "fsm.v:122" *)
  wire [3:0] _000_;
  (* src = "fsm.v:122" *)
  wire _001_;
  (* src = "fsm.v:109" *)
  wire [8:0] _002_;
  (* src = "fsm.v:122" *)
  wire [3:0] _003_;
  (* src = "fsm.v:109" *)
  wire [8:0] _004_;
  (* src = "fsm.v:122" *)
  wire _005_;
  (* src = "fsm.v:122" *)
  wire _006_;
  (* src = "fsm.v:122" *)
  wire _007_;
  (* src = "fsm.v:122" *)
  wire _008_;
  (* src = "fsm.v:122" *)
  wire [8:0] _009_;
  (* src = "fsm.v:122" *)
  wire [8:0] _010_;
  (* src = "fsm.v:122" *)
  wire [8:0] _011_;
  (* src = "fsm.v:122" *)
  wire [8:0] _012_;
  (* src = "fsm.v:122" *)
  wire [8:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire [1:0] _086_;
  wire [1:0] _087_;
  wire [1:0] _088_;
  wire [1:0] _089_;
  wire [3:0] _090_;
  wire [1:0] _091_;
  wire _092_;
  wire [3:0] _093_;
  wire [1:0] _094_;
  wire _095_;
  wire [3:0] _096_;
  wire [1:0] _097_;
  wire _098_;
  wire [3:0] _099_;
  wire [1:0] _100_;
  wire _101_;
  wire [3:0] _102_;
  wire [1:0] _103_;
  wire _104_;
  wire [3:0] _105_;
  wire [1:0] _106_;
  wire _107_;
  wire [3:0] _108_;
  wire [1:0] _109_;
  wire _110_;
  wire [3:0] _111_;
  wire [1:0] _112_;
  wire _113_;
  wire [1:0] _114_;
  wire [1:0] _115_;
  wire [1:0] _116_;
  wire [1:0] _117_;
  wire _118_;
  wire [2:0] _119_;
  wire _120_;
  wire [2:0] _121_;
  wire _122_;
  wire [2:0] _123_;
  wire _124_;
  wire [2:0] _125_;
  wire _126_;
  wire [2:0] _127_;
  wire _128_;
  wire [2:0] _129_;
  wire _130_;
  wire [2:0] _131_;
  wire _132_;
  wire [2:0] _133_;
  wire _134_;
  wire [2:0] _135_;
  wire _136_;
  wire [2:0] _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire [3:0] _141_;
  wire [8:0] _142_;
  wire [8:0] _143_;
  wire [8:0] _144_;
  wire [8:0] _145_;
  wire [8:0] _146_;
  wire [8:0] _147_;
  wire [8:0] _148_;
  wire [8:0] _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  (* src = "fsm.v:146" *)
  wire _154_;
  (* src = "fsm.v:154" *)
  wire _155_;
  (* src = "fsm.v:146" *)
  wire _156_;
  (* src = "fsm.v:154" *)
  wire _157_;
  (* src = "fsm.v:158" *)
  wire _158_;
  (* src = "fsm.v:137" *)
  wire _159_;
  (* src = "fsm.v:162" *)
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _164_;
  (* src = "fsm.v:126|<techmap.v>:428" *)
  wire _165_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _166_;
  (* src = "fsm.v:126|<techmap.v>:428" *)
  wire _167_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _168_;
  (* src = "fsm.v:126|<techmap.v>:428" *)
  wire _169_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _170_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _171_;
  wire _172_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _173_;
  wire _174_;
  wire [8:0] _175_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [53:0] _176_;
  (* src = "fsm.v:126|<techmap.v>:428" *)
  wire [8:0] _177_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _178_;
  (* src = "fsm.v:126|<techmap.v>:432" *)
  wire [1:0] _179_;
  (* src = "fsm.v:126|<techmap.v>:428" *)
  wire _180_;
  wire [8:0] _181_;
  wire [8:0] _182_;
  (* src = "fsm.v:126|<techmap.v>:445" *)
  wire _183_;
  (* src = "fsm.v:126|<techmap.v>:445" *)
  wire _184_;
  (* src = "fsm.v:63" *)
  wire [3:0] FIFOcontinue;
  (* src = "fsm.v:22" *)
  input FIFOcontinue0;
  (* src = "fsm.v:23" *)
  input FIFOcontinue1;
  (* src = "fsm.v:24" *)
  input FIFOcontinue2;
  (* src = "fsm.v:25" *)
  input FIFOcontinue3;
  (* src = "fsm.v:68" *)
  wire [3:0] FIFOcontinueOR;
  (* src = "fsm.v:64" *)
  wire [3:0] FIFOempty;
  (* src = "fsm.v:26" *)
  input FIFOempty0;
  (* src = "fsm.v:27" *)
  input FIFOempty1;
  (* src = "fsm.v:28" *)
  input FIFOempty2;
  (* src = "fsm.v:29" *)
  input FIFOempty3;
  (* src = "fsm.v:66" *)
  wire [3:0] FIFOerror;
  (* src = "fsm.v:30" *)
  input FIFOerror0;
  (* src = "fsm.v:31" *)
  input FIFOerror1;
  (* src = "fsm.v:32" *)
  input FIFOerror2;
  (* src = "fsm.v:33" *)
  input FIFOerror3;
  (* src = "fsm.v:65" *)
  wire [3:0] FIFOfull;
  (* src = "fsm.v:34" *)
  input FIFOfull0;
  (* src = "fsm.v:35" *)
  input FIFOfull1;
  (* src = "fsm.v:36" *)
  input FIFOfull2;
  (* src = "fsm.v:37" *)
  input FIFOfull3;
  (* src = "fsm.v:62" *)
  wire [3:0] FIFOpause;
  (* src = "fsm.v:17" *)
  input FIFOpause0;
  (* src = "fsm.v:18" *)
  input FIFOpause1;
  (* src = "fsm.v:19" *)
  input FIFOpause2;
  (* src = "fsm.v:20" *)
  input FIFOpause3;
  (* src = "fsm.v:67" *)
  wire [3:0] FIFOpauseOR;
  (* src = "fsm.v:13" *)
  input clk;
  (* src = "fsm.v:41" *)
  output [3:0] continue;
  (* src = "fsm.v:39" *)
  output [3:0] error_full;
  (* src = "fsm.v:42" *)
  output idle;
  (* src = "fsm.v:15" *)
  input init;
  (* src = "fsm.v:49" *)
  reg [8:0] nxtState;
  (* src = "fsm.v:40" *)
  output [3:0] pause;
  (* src = "fsm.v:14" *)
  input reset;
  (* src = "fsm.v:49" *)
  reg [8:0] state;
  assign _086_[0] = _141_[0] |(* src = "fsm.v:137" *)  _141_[1];
  assign _086_[1] = _141_[2] |(* src = "fsm.v:137" *)  _141_[3];
  assign _159_ = _086_[0] |(* src = "fsm.v:137" *)  _086_[1];
  assign _087_[0] = FIFOpauseOR[0] |(* src = "fsm.v:158" *)  FIFOpauseOR[1];
  assign _140_ = _087_[0] |(* src = "fsm.v:158" *)  _087_[1];
  assign _088_[0] = FIFOcontinueOR[0] |(* src = "fsm.v:158" *)  FIFOcontinueOR[1];
  assign _139_ = _088_[0] |(* src = "fsm.v:158" *)  _088_[1];
  assign _089_[0] = FIFOerror0 |(* src = "fsm.v:162" *)  FIFOerror1;
  assign _089_[1] = FIFOerror2 |(* src = "fsm.v:162" *)  FIFOerror3;
  assign _160_ = _089_[0] |(* src = "fsm.v:162" *)  _089_[1];
  assign _090_[3] = state[6] |(* src = "fsm.v:126" *)  _142_[7];
  assign _091_[1] = _090_[2] |(* src = "fsm.v:126" *)  _090_[3];
  assign _092_ = _091_[0] |(* src = "fsm.v:126" *)  _091_[1];
  assign _022_ = _092_ |(* src = "fsm.v:126" *)  state[8];
  assign _093_[0] = state[0] |(* src = "fsm.v:126" *)  _143_[1];
  assign _094_[0] = _093_[0] |(* src = "fsm.v:126" *)  _090_[1];
  assign _095_ = _094_[0] |(* src = "fsm.v:126" *)  _094_[1];
  assign _150_ = _095_ |(* src = "fsm.v:126" *)  state[8];
  assign _096_[0] = _144_[0] |(* src = "fsm.v:126" *)  state[1];
  assign _097_[0] = _096_[0] |(* src = "fsm.v:126" *)  _090_[1];
  assign _098_ = _097_[0] |(* src = "fsm.v:126" *)  _094_[1];
  assign _151_ = _098_ |(* src = "fsm.v:126" *)  state[8];
  assign _099_[1] = _145_[2] |(* src = "fsm.v:126" *)  state[3];
  assign _100_[0] = _090_[0] |(* src = "fsm.v:126" *)  _099_[1];
  assign _101_ = _100_[0] |(* src = "fsm.v:126" *)  _094_[1];
  assign _152_ = _101_ |(* src = "fsm.v:126" *)  state[8];
  assign _102_[1] = state[2] |(* src = "fsm.v:126" *)  _146_[3];
  assign _103_[0] = _090_[0] |(* src = "fsm.v:126" *)  _102_[1];
  assign _094_[1] = _090_[2] |(* src = "fsm.v:126" *)  _093_[3];
  assign _104_ = _103_[0] |(* src = "fsm.v:126" *)  _094_[1];
  assign _153_ = _104_ |(* src = "fsm.v:126" *)  state[8];
  assign _090_[2] = state[4] |(* src = "fsm.v:126" *)  state[5];
  assign _105_[3] = _147_[6] |(* src = "fsm.v:126" *)  state[7];
  assign _091_[0] = _090_[0] |(* src = "fsm.v:126" *)  _090_[1];
  assign _106_[1] = _090_[2] |(* src = "fsm.v:126" *)  _105_[3];
  assign _107_ = _091_[0] |(* src = "fsm.v:126" *)  _106_[1];
  assign _018_ = _107_ |(* src = "fsm.v:126" *)  state[8];
  assign _108_[2] = state[4] |(* src = "fsm.v:126" *)  _148_[5];
  assign _109_[1] = _108_[2] |(* src = "fsm.v:126" *)  _093_[3];
  assign _110_ = _091_[0] |(* src = "fsm.v:126" *)  _109_[1];
  assign _017_ = _110_ |(* src = "fsm.v:126" *)  state[8];
  assign _090_[0] = state[0] |(* src = "fsm.v:126" *)  state[1];
  assign _090_[1] = state[2] |(* src = "fsm.v:126" *)  state[3];
  assign _111_[2] = _149_[4] |(* src = "fsm.v:126" *)  state[5];
  assign _093_[3] = state[6] |(* src = "fsm.v:126" *)  state[7];
  assign _112_[1] = _111_[2] |(* src = "fsm.v:126" *)  _093_[3];
  assign _113_ = _091_[0] |(* src = "fsm.v:126" *)  _112_[1];
  assign _016_ = _113_ |(* src = "fsm.v:126" *)  state[8];
  assign _054_ = _079_ | _022_;
  assign _056_ = _080_ | _022_;
  assign _058_ = _081_ | _022_;
  assign _060_ = _082_ | _022_;
  assign _114_[0] = _072_ | _071_;
  assign _114_[1] = _070_ | _069_;
  assign _039_ = _114_[0] | _114_[1];
  assign _115_[0] = _075_ | _074_;
  assign _115_[1] = _073_ | _072_;
  assign _046_ = _115_[0] | _115_[1];
  assign _116_[0] = _078_ | _077_;
  assign _116_[1] = _076_ | _072_;
  assign _052_ = _116_[0] | _116_[1];
  assign _117_[0] = _072_ | _085_;
  assign _117_[1] = _084_ | _083_;
  assign _066_ = _117_[0] | _117_[1];
  assign _118_ = _163_ | _162_;
  assign _014_ = _118_ | _161_;
  assign _119_[0] = _172_ |(* src = "fsm.v:126|<techmap.v>:445" *)  _014_;
  assign _119_[1] = _174_ |(* src = "fsm.v:126|<techmap.v>:445" *)  _021_;
  assign _119_[2] = _125_[2] |(* src = "fsm.v:126|<techmap.v>:445" *)  _123_[2];
  assign _120_ = _119_[0] |(* src = "fsm.v:126|<techmap.v>:445" *)  _119_[1];
  assign _184_ = _120_ |(* src = "fsm.v:126|<techmap.v>:445" *)  _119_[2];
  assign _121_[1] = _176_[18] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[27];
  assign _122_ = _121_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _121_[1];
  assign _123_[1] = _176_[19] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[28];
  assign _124_ = _123_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _123_[1];
  assign _177_[1] = _124_ |(* src = "fsm.v:126|<techmap.v>:441" *)  _123_[2];
  assign _125_[1] = _176_[20] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[29];
  assign _126_ = _125_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _125_[1];
  assign _177_[2] = _126_ |(* src = "fsm.v:126|<techmap.v>:441" *)  _125_[2];
  assign _127_[1] = _176_[22] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[31];
  assign _128_ = _127_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _127_[1];
  assign _129_[0] = _176_[3] |(* src = "fsm.v:126|<techmap.v>:441" *)  _014_;
  assign _129_[1] = _176_[21] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[30];
  assign _130_ = _129_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _129_[1];
  assign _131_[1] = _176_[23] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[32];
  assign _132_ = _131_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _131_[1];
  assign _133_[1] = _176_[24] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[33];
  assign _134_ = _133_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _133_[1];
  assign _135_[1] = _176_[25] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[34];
  assign _136_ = _135_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _135_[1];
  assign _137_[1] = _176_[26] |(* src = "fsm.v:126|<techmap.v>:441" *)  _176_[35];
  assign _138_ = _137_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _137_[1];
  assign _180_ = _179_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _162_;
  assign _169_ = _168_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _162_;
  assign _167_ = _166_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _162_;
  assign _183_ = _161_ |(* src = "fsm.v:126|<techmap.v>:445" *)  _162_;
  assign _165_ = _164_[0] |(* src = "fsm.v:126|<techmap.v>:441" *)  _162_;
  assign _088_[1] = FIFOcontinueOR[2] |(* src = "fsm.v:146" *)  FIFOcontinueOR[3];
  assign _087_[1] = FIFOpauseOR[2] |(* src = "fsm.v:154" *)  FIFOpauseOR[3];
  assign _154_ = ~(* src = "fsm.v:146" *) _139_;
  assign _155_ = ~(* src = "fsm.v:154" *) _140_;
  assign _172_ = ~(* src = "fsm.v:126" *) _022_;
  assign _125_[2] = ~(* src = "fsm.v:126" *) _150_;
  assign _123_[2] = ~(* src = "fsm.v:126" *) _151_;
  assign _021_ = ~(* src = "fsm.v:126" *) _152_;
  assign _174_ = ~(* src = "fsm.v:126" *) _153_;
  assign _161_ = ~(* src = "fsm.v:126" *) _018_;
  assign _162_ = ~(* src = "fsm.v:126" *) _017_;
  assign _163_ = ~(* src = "fsm.v:126" *) _016_;
  assign FIFOpauseOR[0] = FIFOfull0 |(* src = "fsm.v:97" *)  FIFOpause0;
  assign FIFOpauseOR[1] = FIFOfull1 |(* src = "fsm.v:98" *)  FIFOpause1;
  assign FIFOpauseOR[2] = FIFOfull2 |(* src = "fsm.v:99" *)  FIFOpause2;
  assign FIFOpauseOR[3] = FIFOfull3 |(* src = "fsm.v:100" *)  FIFOpause3;
  assign FIFOcontinueOR[0] = FIFOempty0 |(* src = "fsm.v:103" *)  FIFOcontinue0;
  assign FIFOcontinueOR[1] = FIFOempty1 |(* src = "fsm.v:104" *)  FIFOcontinue1;
  assign FIFOcontinueOR[2] = FIFOempty2 |(* src = "fsm.v:105" *)  FIFOcontinue2;
  assign FIFOcontinueOR[3] = FIFOempty3 |(* src = "fsm.v:106" *)  FIFOcontinue3;
  assign _156_ = _140_ &(* src = "fsm.v:146" *)  _154_;
  assign _157_ = _139_ &(* src = "fsm.v:154" *)  _155_;
  assign _158_ = _140_ &(* src = "fsm.v:158" *)  _139_;
  assign _012_[0] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[0];
  assign _012_[1] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[1];
  assign _012_[2] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[2];
  assign _012_[3] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[3];
  assign _012_[4] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[4];
  assign _012_[5] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[5];
  assign _012_[6] = _158_ ? (* src = "fsm.v:158" *) 1'h1 : _011_[6];
  assign _012_[7] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[7];
  assign _012_[8] = _158_ ? (* src = "fsm.v:158" *) 1'h0 : _011_[8];
  assign _011_[0] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[0];
  assign _011_[1] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[1];
  assign _011_[2] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[2];
  assign _011_[3] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[3];
  assign _011_[4] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[4];
  assign _011_[5] = _157_ ? (* src = "fsm.v:154" *) 1'h1 : _010_[5];
  assign _011_[6] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[6];
  assign _011_[7] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[7];
  assign _011_[8] = _157_ ? (* src = "fsm.v:154" *) 1'h0 : _010_[8];
  assign _010_[0] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[0];
  assign _010_[1] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[1];
  assign _010_[2] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[2];
  assign _010_[3] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[3];
  assign _010_[4] = _156_ ? (* src = "fsm.v:146" *) 1'h1 : state[4];
  assign _010_[5] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[5];
  assign _010_[6] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[6];
  assign _010_[7] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[7];
  assign _010_[8] = _156_ ? (* src = "fsm.v:146" *) 1'h0 : state[8];
  assign _009_[0] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[0];
  assign _009_[1] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[1];
  assign _009_[2] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[2];
  assign _009_[3] = _159_ ? (* src = "fsm.v:137" *) 1'h1 : state[3];
  assign _009_[4] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[4];
  assign _009_[5] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[5];
  assign _009_[6] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[6];
  assign _009_[7] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[7];
  assign _009_[8] = _159_ ? (* src = "fsm.v:137" *) 1'h0 : state[8];
  assign _001_ = ~(* src = "fsm.v:137" *) _159_;
  assign _175_[0] = reset ? (* src = "fsm.v:252" *) 1'h1 : state[0];
  assign _175_[1] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[1];
  assign _175_[2] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[2];
  assign _175_[3] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[3];
  assign _175_[4] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[4];
  assign _175_[5] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[5];
  assign _175_[6] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[6];
  assign _175_[7] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[7];
  assign _175_[8] = reset ? (* src = "fsm.v:252" *) 1'h0 : state[8];
  assign _013_[0] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[0];
  assign _013_[1] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[1];
  assign _013_[2] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[2];
  assign _013_[3] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[3];
  assign _013_[4] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[4];
  assign _013_[5] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[5];
  assign _013_[6] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[6];
  assign _013_[7] = _160_ ? (* src = "fsm.v:162" *) 1'h1 : _012_[7];
  assign _013_[8] = _160_ ? (* src = "fsm.v:162" *) 1'h0 : _012_[8];
  assign _181_[0] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[0];
  assign _181_[1] = init ? (* src = "fsm.v:113" *) 1'h1 : nxtState[1];
  assign _181_[2] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[2];
  assign _181_[3] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[3];
  assign _181_[4] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[4];
  assign _181_[5] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[5];
  assign _181_[6] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[6];
  assign _181_[7] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[7];
  assign _181_[8] = init ? (* src = "fsm.v:113" *) 1'h0 : nxtState[8];
  assign _002_[0] = reset ? (* src = "fsm.v:110" *) nxtState[0] : _181_[0];
  assign _002_[1] = reset ? (* src = "fsm.v:110" *) nxtState[1] : _181_[1];
  assign _002_[2] = reset ? (* src = "fsm.v:110" *) nxtState[2] : _181_[2];
  assign _002_[3] = reset ? (* src = "fsm.v:110" *) nxtState[3] : _181_[3];
  assign _002_[4] = reset ? (* src = "fsm.v:110" *) nxtState[4] : _181_[4];
  assign _002_[5] = reset ? (* src = "fsm.v:110" *) nxtState[5] : _181_[5];
  assign _002_[6] = reset ? (* src = "fsm.v:110" *) nxtState[6] : _181_[6];
  assign _002_[7] = reset ? (* src = "fsm.v:110" *) nxtState[7] : _181_[7];
  assign _002_[8] = reset ? (* src = "fsm.v:110" *) nxtState[8] : _181_[8];
  assign _182_[0] = init ? (* src = "fsm.v:113" *) state[0] : nxtState[0];
  assign _182_[1] = init ? (* src = "fsm.v:113" *) state[1] : nxtState[1];
  assign _182_[2] = init ? (* src = "fsm.v:113" *) state[2] : nxtState[2];
  assign _182_[3] = init ? (* src = "fsm.v:113" *) state[3] : nxtState[3];
  assign _182_[4] = init ? (* src = "fsm.v:113" *) state[4] : nxtState[4];
  assign _182_[5] = init ? (* src = "fsm.v:113" *) state[5] : nxtState[5];
  assign _182_[6] = init ? (* src = "fsm.v:113" *) state[6] : nxtState[6];
  assign _182_[7] = init ? (* src = "fsm.v:113" *) state[7] : nxtState[7];
  assign _182_[8] = init ? (* src = "fsm.v:113" *) state[8] : nxtState[8];
  assign _004_[0] = reset ? (* src = "fsm.v:110" *) 1'h1 : _182_[0];
  assign _004_[1] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[1];
  assign _004_[2] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[2];
  assign _004_[3] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[3];
  assign _004_[4] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[4];
  assign _004_[5] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[5];
  assign _004_[6] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[6];
  assign _004_[7] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[7];
  assign _004_[8] = reset ? (* src = "fsm.v:110" *) 1'h0 : _182_[8];
  assign nxtState[0] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _122_ : 1'h1;
  assign nxtState[1] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _177_[1] : 1'h0;
  assign nxtState[2] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _177_[2] : 1'h0;
  assign nxtState[3] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _130_ : 1'h0;
  assign nxtState[4] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _128_ : 1'h0;
  assign nxtState[5] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _132_ : 1'h0;
  assign nxtState[6] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _134_ : 1'h0;
  assign nxtState[7] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _136_ : 1'h0;
  assign nxtState[8] = _184_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _138_ : 1'h0;
  assign _000_[2] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _180_ : 1'h0;
  assign _003_[2] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _173_[0] : 1'h1;
  assign _003_[3] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _171_[0] : 1'h1;
  assign _003_[0] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _170_[0] : 1'h1;
  assign _000_[0] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _169_ : 1'h0;
  assign _000_[1] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _167_ : 1'h0;
  assign _000_[3] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _165_ : 1'h0;
  assign _003_[1] = _183_ ? (* src = "fsm.v:126|<techmap.v>:445" *) _178_[0] : 1'h1;
  assign _023_ = ~FIFOerror0;
  assign _024_ = ~_054_;
  assign _025_ = ~FIFOerror1;
  assign _026_ = ~_056_;
  assign _027_ = ~FIFOerror2;
  assign _028_ = ~_058_;
  assign _029_ = ~FIFOerror3;
  assign _030_ = ~_060_;
  assign _031_ = ~FIFOpauseOR[0];
  assign _005_ = ~FIFOcontinueOR[0];
  assign _033_ = ~FIFOpauseOR[1];
  assign _007_ = ~FIFOcontinueOR[2];
  assign _034_ = ~FIFOpauseOR[2];
  assign _019_ = ~_046_;
  assign _035_ = ~FIFOpauseOR[3];
  assign _008_ = ~FIFOcontinueOR[3];
  assign _020_ = ~_052_;
  assign _032_ = ~_066_;
  assign _006_ = ~FIFOcontinueOR[1];
  assign _015_ = ~_039_;
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[0] <= _004_[0];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[1] <= _004_[1];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[2] <= _004_[2];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[3] <= _004_[3];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[4] <= _004_[4];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[5] <= _004_[5];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[6] <= _004_[6];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[7] <= _004_[7];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      state[8] <= _004_[8];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[0] <= _002_[0];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[1] <= _002_[1];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[2] <= _002_[2];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[3] <= _002_[3];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[4] <= _002_[4];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[5] <= _002_[5];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[6] <= _002_[6];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[7] <= _002_[7];
  (* src = "fsm.v:109" *)
  always @(posedge clk)
      nxtState[8] <= _002_[8];
  \$_DLATCH_P_  _451_ (
    .D(1'h1),
    .E(_024_),
    .Q(error_full[0])
  );
  \$_DLATCH_P_  _452_ (
    .D(1'h1),
    .E(_026_),
    .Q(error_full[1])
  );
  \$_DLATCH_P_  _453_ (
    .D(1'h1),
    .E(_028_),
    .Q(error_full[2])
  );
  \$_DLATCH_P_  _454_ (
    .D(1'h1),
    .E(_030_),
    .Q(error_full[3])
  );
  \$_DLATCH_P_  _455_ (
    .D(_003_[0]),
    .E(_032_),
    .Q(pause[0])
  );
  \$_DLATCH_P_  _456_ (
    .D(_003_[1]),
    .E(_015_),
    .Q(pause[1])
  );
  \$_DLATCH_P_  _457_ (
    .D(_003_[2]),
    .E(_019_),
    .Q(pause[2])
  );
  \$_DLATCH_P_  _458_ (
    .D(_003_[3]),
    .E(_020_),
    .Q(pause[3])
  );
  \$_DLATCH_P_  _459_ (
    .D(_000_[0]),
    .E(_032_),
    .Q(continue[0])
  );
  \$_DLATCH_P_  _460_ (
    .D(_000_[1]),
    .E(_015_),
    .Q(continue[1])
  );
  \$_DLATCH_P_  _461_ (
    .D(_000_[2]),
    .E(_019_),
    .Q(continue[2])
  );
  \$_DLATCH_P_  _462_ (
    .D(_000_[3]),
    .E(_020_),
    .Q(continue[3])
  );
  \$_DLATCH_P_  _463_ (
    .D(_001_),
    .E(_021_),
    .Q(idle)
  );
  assign _141_[0] = FIFOempty0 ^(* src = "fsm.v:137" *)  1'h1;
  assign _141_[1] = FIFOempty1 ^(* src = "fsm.v:137" *)  1'h1;
  assign _141_[2] = FIFOempty2 ^(* src = "fsm.v:137" *)  1'h1;
  assign _141_[3] = FIFOempty3 ^(* src = "fsm.v:137" *)  1'h1;
  assign _142_[7] = state[7] ^(* src = "fsm.v:126" *)  1'h1;
  assign _143_[1] = state[1] ^(* src = "fsm.v:126" *)  1'h1;
  assign _144_[0] = state[0] ^(* src = "fsm.v:126" *)  1'h1;
  assign _145_[2] = state[2] ^(* src = "fsm.v:126" *)  1'h1;
  assign _146_[3] = state[3] ^(* src = "fsm.v:126" *)  1'h1;
  assign _147_[6] = state[6] ^(* src = "fsm.v:126" *)  1'h1;
  assign _148_[5] = state[5] ^(* src = "fsm.v:126" *)  1'h1;
  assign _149_[4] = state[4] ^(* src = "fsm.v:126" *)  1'h1;
  assign _053_ = _172_ & _023_;
  assign _079_ = _172_ & _053_;
  assign _055_ = _172_ & _025_;
  assign _080_ = _172_ & _055_;
  assign _057_ = _172_ & _027_;
  assign _081_ = _172_ & _057_;
  assign _059_ = _172_ & _029_;
  assign _082_ = _172_ & _059_;
  assign _040_ = _017_ & _018_;
  assign _061_ = _161_ & _031_;
  assign _062_ = _005_ & _061_;
  assign _063_ = _161_ & _062_;
  assign _084_ = _162_ & _064_;
  assign _065_ = _163_ & _031_;
  assign _085_ = _163_ & _065_;
  assign _068_ = _006_ & _067_;
  assign _036_ = _161_ & _068_;
  assign _069_ = _161_ & _036_;
  assign _037_ = _162_ & _006_;
  assign _070_ = _162_ & _037_;
  assign _038_ = _163_ & _033_;
  assign _071_ = _163_ & _038_;
  assign _042_ = _007_ & _041_;
  assign _043_ = _161_ & _042_;
  assign _073_ = _161_ & _043_;
  assign _075_ = _163_ & _045_;
  assign _047_ = _161_ & _035_;
  assign _048_ = _008_ & _047_;
  assign _050_ = _162_ & _008_;
  assign _077_ = _162_ & _050_;
  assign _051_ = _163_ & _035_;
  assign _078_ = _163_ & _051_;
  assign _083_ = _161_ & _063_;
  assign _064_ = _162_ & _005_;
  assign _067_ = _161_ & _033_;
  assign _072_ = _016_ & _040_;
  assign _041_ = _161_ & _034_;
  assign _044_ = _162_ & _007_;
  assign _074_ = _162_ & _044_;
  assign _045_ = _163_ & _034_;
  assign _049_ = _161_ & _048_;
  assign _076_ = _161_ & _049_;
  assign _121_[0] = _175_[0] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _123_[0] = _175_[1] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _125_[0] = _175_[2] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _176_[3] = _175_[3] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _127_[0] = _175_[4] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _131_[0] = _175_[5] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _133_[0] = _175_[6] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _135_[0] = _175_[7] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _137_[0] = _175_[8] &(* src = "fsm.v:126|<techmap.v>:434" *)  _172_;
  assign _176_[18] = _013_[0] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[19] = _013_[1] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[20] = _013_[2] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[21] = _013_[3] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[22] = _013_[4] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[23] = _013_[5] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[24] = _013_[6] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[25] = _013_[7] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[26] = _013_[8] &(* src = "fsm.v:126|<techmap.v>:434" *)  _174_;
  assign _176_[27] = _009_[0] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[28] = _009_[1] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[29] = _009_[2] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[30] = _009_[3] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[31] = _009_[4] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[32] = _009_[5] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[33] = _009_[6] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[34] = _009_[7] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _176_[35] = _009_[8] &(* src = "fsm.v:126|<techmap.v>:434" *)  _021_;
  assign _179_[0] = FIFOcontinueOR[2] &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _173_[0] = _007_ &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _171_[0] = _008_ &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _170_[0] = _005_ &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _168_[0] = FIFOcontinueOR[0] &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _166_[0] = FIFOcontinueOR[1] &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _164_[0] = FIFOcontinueOR[3] &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign _178_[0] = _006_ &(* src = "fsm.v:126|<techmap.v>:434" *)  _161_;
  assign FIFOcontinue = { FIFOcontinue3, FIFOcontinue2, FIFOcontinue1, FIFOcontinue0 };
  assign FIFOempty = { FIFOempty3, FIFOempty2, FIFOempty1, FIFOempty0 };
  assign FIFOerror = { FIFOerror3, FIFOerror2, FIFOerror1, FIFOerror0 };
  assign FIFOfull = { FIFOfull3, FIFOfull2, FIFOfull1, FIFOfull0 };
  assign FIFOpause = { FIFOpause3, FIFOpause2, FIFOpause1, FIFOpause0 };
endmodule
